// @generated drizzle-zero signature:sha256:7252eb51fa444165e779e7249d8f79930531604d34f54cb3adfaa20387702b47
// This file was automatically generated by drizzle-zero.
// You should NOT make any changes in this file as it will be overwritten.

const widgetsTable = {
  name: 'widgets',
  columns: {
    id: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    name: {
      type: 'string',
      optional: false,
      customType: null as unknown as string,
    },
    size: {
      type: 'number',
      optional: false,
      customType: null as unknown as number,
    },
  },
  primaryKey: ['id'],
} as const;
/**
 * The Zero schema object.
 * This type is auto-generated from your Drizzle schema definition.
 */
export const schema = {
  tables: {
    widgets: widgetsTable,
  },
  relationships: {},
  enableLegacyQueries: false,
  enableLegacyMutators: false,
} as const;

/**
 * Represents the Zero schema type.
 * This type is auto-generated from your Drizzle schema definition.
 */
export type Schema = typeof schema;
