### GET
GET http://localhost:3000/?foo=123&bar=456
Accept: application/json
X-Konker: Plonker


### GET
GET https://k6xj6hudxzsjentrgv4aoco6sa0rhdrp.lambda-url.eu-west-1.on.aws/
Accept: application/json
X-Konker: Plonker


### GET
GET https://api.boilerplate.development.konker.dev/
Accept: application/json
X-Konker: Plonker


### GET
https://backend-boilerplate.hetzner.konker.dev/
Accept: application/json
X-Konker: Plonker


### GET
GET https://backend-boilerplate.hetzner.konker.dev/
Accept: application/json
X-Konker: Plonker


### GET
GET http://backend-boilerplate.hetzner.konker.dev/
Accept: application/json
X-Konker: Plonker


### GET
GET https://k3s.hetzner.morningwoodsoftware.com/
Accept: application/json
X-Konker: Plonker


### GET
GET http://k3s.hetzner.morningwoodsoftware.com/
Accept: application/json
X-Konker: Plonker

