apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zero-sync-data
  labels:
    app.kubernetes.io/name: zero-sync
    app.kubernetes.io/component: sync
    app.kubernetes.io/managed-by: kustomize
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: hcloud-volumes
  resources:
    requests:
      storage: REPLACE_STORAGE_SIZE
