import baseConfig from '@konker.dev/common-config/configs/eslint.config-base.mjs';
import importX from 'eslint-plugin-import-x';

export default [
  ...baseConfig,
  {
    ignores: [
      'dist/',
      'coverage/',
      'scripts/',
      'vitest.config.ts',
      'tsup.config.ts',
      '.deploy',
      '**/.sst/',
      '**/sst.config.ts',
      'sst-env.d.ts',
      // Generated by drizzle-zero (`pnpm run zero:generate`); never hand-edited
      // or reformatted, so keep linters/formatters off it to avoid drift.
      'src/zero-sync/schema.gen.ts',
    ],
  },
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    // Isomorphic Zero modules are imported by the browser (frontend) via the
    // package's `./zero-sync/*` exports. Guard the boundary so no server-only
    // code (Effect/hono/postgres/…) can leak into the client bundle.
    files: ['src/zero-sync/**/*.ts'],
    plugins: { 'import-x': importX },
    settings: {
      'import-x/resolver': { typescript: { project: import.meta.dirname } },
    },
    rules: {
      // Allowlist: src/zero-sync may only reach its own siblings — never any
      // other src/ module (all of which is, or may become, server code).
      'import-x/no-restricted-paths': [
        'error',
        {
          zones: [
            {
              target: './src/zero-sync',
              from: './src',
              except: ['./zero-sync'],
              message:
                'src/zero-sync is isomorphic (browser-safe): it must not import other src/ modules. Keep it to @rocicorp/zero + zod + siblings.',
            },
          ],
        },
      ],
      // Belt-and-braces: block direct imports of server-only / node packages,
      // which the path zone above cannot see.
      'no-restricted-imports': [
        'error',
        {
          patterns: [
            {
              group: [
                'effect',
                'effect/*',
                '@effect/*',
                'hono',
                'hono/*',
                '@hono/*',
                'postgres',
                'drizzle-orm',
                'drizzle-orm/*',
                'jose',
                'aws-lambda',
                '@opentelemetry/*',
                'dotenv',
                '@dotenvx/*',
                'node:*',
              ],
              message:
                'src/zero-sync is browser-safe: no server-only or node built-in deps. Allowed: @rocicorp/zero, zod.',
            },
          ],
        },
      ],
    },
  },
];
