export const grammar = [
  '[unk]',
  'a',
  'b',
  'c',
  'd',
  'e',
  'f',
  'g',
  'h',
  'one',
  'two',
  'three',
  'four',
  'five',
  'six',
  'seven',
  'eight',
  'to',
  'takes',
  'captures',
  'pawn',
  'knight',
  'N',
  'bishop',
  'rook',
  'R',
  'queen',
  'Q',
  'king',
  'K',
  'castle',
  'kingside',
  'queenside',
  'short',
  'long',
  'check',
  'checkmate',
  'mate',
  'undo',
  'resign',
  'draw',
  'promote',
  'promotes',
  'promotion',
  'en passant',
  'a one',
  'a two',
  'a three',
  'a four',
  'a five',
  'a six',
  'a seven',
  'a eight',
  'b one',
  'b two',
  'b three',
  'b four',
  'b five',
  'b six',
  'b seven',
  'b eight',
  'c one',
  'c two',
  'c three',
  'c four',
  'c five',
  'c six',
  'c seven',
  'c eight',
  'd one',
  'd two',
  'd three',
  'd four',
  'd five',
  'd six',
  'd seven',
  'd eight',
  'e one',
  'e two',
  'e three',
  'e four',
  'e five',
  'e six',
  'e seven',
  'e eight',
  'f one',
  'f two',
  'f three',
  'f four',
  'f five',
  'f six',
  'f seven',
  'f eight',
  'g one',
  'g two',
  'g three',
  'g four',
  'g five',
  'g six',
  'g seven',
  'g eight',
  'h one',
  'h two',
  'h three',
  'h four',
  'h five',
  'h six',
  'h seven',
  'h eight',
  'N a one',
  'knight to a one',
  'knight a one',
  'knight takes a one',
  'knight captures a one',
  'N a two',
  'knight to a two',
  'knight a two',
  'knight takes a two',
  'knight captures a two',
  'N a three',
  'knight to a three',
  'knight a three',
  'knight takes a three',
  'knight captures a three',
  'N a four',
  'knight to a four',
  'knight a four',
  'knight takes a four',
  'knight captures a four',
  'N a five',
  'knight to a five',
  'knight a five',
  'knight takes a five',
  'knight captures a five',
  'N a six',
  'knight to a six',
  'knight a six',
  'knight takes a six',
  'knight captures a six',
  'N a seven',
  'knight to a seven',
  'knight a seven',
  'knight takes a seven',
  'knight captures a seven',
  'N a eight',
  'knight to a eight',
  'knight a eight',
  'knight takes a eight',
  'knight captures a eight',
  'N b one',
  'knight to b one',
  'knight b one',
  'knight takes b one',
  'knight captures b one',
  'N b two',
  'knight to b two',
  'knight b two',
  'knight takes b two',
  'knight captures b two',
  'N b three',
  'knight to b three',
  'knight b three',
  'knight takes b three',
  'knight captures b three',
  'N b four',
  'knight to b four',
  'knight b four',
  'knight takes b four',
  'knight captures b four',
  'N b five',
  'knight to b five',
  'knight b five',
  'knight takes b five',
  'knight captures b five',
  'N b six',
  'knight to b six',
  'knight b six',
  'knight takes b six',
  'knight captures b six',
  'N b seven',
  'knight to b seven',
  'knight b seven',
  'knight takes b seven',
  'knight captures b seven',
  'N b eight',
  'knight to b eight',
  'knight b eight',
  'knight takes b eight',
  'knight captures b eight',
  'N c one',
  'knight to c one',
  'knight c one',
  'knight takes c one',
  'knight captures c one',
  'N c two',
  'knight to c two',
  'knight c two',
  'knight takes c two',
  'knight captures c two',
  'N c three',
  'knight to c three',
  'knight c three',
  'knight takes c three',
  'knight captures c three',
  'N c four',
  'knight to c four',
  'knight c four',
  'knight takes c four',
  'knight captures c four',
  'N c five',
  'knight to c five',
  'knight c five',
  'knight takes c five',
  'knight captures c five',
  'N c six',
  'knight to c six',
  'knight c six',
  'knight takes c six',
  'knight captures c six',
  'N c seven',
  'knight to c seven',
  'knight c seven',
  'knight takes c seven',
  'knight captures c seven',
  'N c eight',
  'knight to c eight',
  'knight c eight',
  'knight takes c eight',
  'knight captures c eight',
  'N d one',
  'knight to d one',
  'knight d one',
  'knight takes d one',
  'knight captures d one',
  'N d two',
  'knight to d two',
  'knight d two',
  'knight takes d two',
  'knight captures d two',
  'N d three',
  'knight to d three',
  'knight d three',
  'knight takes d three',
  'knight captures d three',
  'N d four',
  'knight to d four',
  'knight d four',
  'knight takes d four',
  'knight captures d four',
  'N d five',
  'knight to d five',
  'knight d five',
  'knight takes d five',
  'knight captures d five',
  'N d six',
  'knight to d six',
  'knight d six',
  'knight takes d six',
  'knight captures d six',
  'N d seven',
  'knight to d seven',
  'knight d seven',
  'knight takes d seven',
  'knight captures d seven',
  'N d eight',
  'knight to d eight',
  'knight d eight',
  'knight takes d eight',
  'knight captures d eight',
  'N e one',
  'knight to e one',
  'knight e one',
  'knight takes e one',
  'knight captures e one',
  'N e two',
  'knight to e two',
  'knight e two',
  'knight takes e two',
  'knight captures e two',
  'N e three',
  'knight to e three',
  'knight e three',
  'knight takes e three',
  'knight captures e three',
  'N e four',
  'knight to e four',
  'knight e four',
  'knight takes e four',
  'knight captures e four',
  'N e five',
  'knight to e five',
  'knight e five',
  'knight takes e five',
  'knight captures e five',
  'N e six',
  'knight to e six',
  'knight e six',
  'knight takes e six',
  'knight captures e six',
  'N e seven',
  'knight to e seven',
  'knight e seven',
  'knight takes e seven',
  'knight captures e seven',
  'N e eight',
  'knight to e eight',
  'knight e eight',
  'knight takes e eight',
  'knight captures e eight',
  'N f one',
  'knight to f one',
  'knight f one',
  'knight takes f one',
  'knight captures f one',
  'N f two',
  'knight to f two',
  'knight f two',
  'knight takes f two',
  'knight captures f two',
  'N f three',
  'knight to f three',
  'knight f three',
  'knight takes f three',
  'knight captures f three',
  'N f four',
  'knight to f four',
  'knight f four',
  'knight takes f four',
  'knight captures f four',
  'N f five',
  'knight to f five',
  'knight f five',
  'knight takes f five',
  'knight captures f five',
  'N f six',
  'knight to f six',
  'knight f six',
  'knight takes f six',
  'knight captures f six',
  'N f seven',
  'knight to f seven',
  'knight f seven',
  'knight takes f seven',
  'knight captures f seven',
  'N f eight',
  'knight to f eight',
  'knight f eight',
  'knight takes f eight',
  'knight captures f eight',
  'N g one',
  'knight to g one',
  'knight g one',
  'knight takes g one',
  'knight captures g one',
  'N g two',
  'knight to g two',
  'knight g two',
  'knight takes g two',
  'knight captures g two',
  'N g three',
  'knight to g three',
  'knight g three',
  'knight takes g three',
  'knight captures g three',
  'N g four',
  'knight to g four',
  'knight g four',
  'knight takes g four',
  'knight captures g four',
  'N g five',
  'knight to g five',
  'knight g five',
  'knight takes g five',
  'knight captures g five',
  'N g six',
  'knight to g six',
  'knight g six',
  'knight takes g six',
  'knight captures g six',
  'N g seven',
  'knight to g seven',
  'knight g seven',
  'knight takes g seven',
  'knight captures g seven',
  'N g eight',
  'knight to g eight',
  'knight g eight',
  'knight takes g eight',
  'knight captures g eight',
  'N h one',
  'knight to h one',
  'knight h one',
  'knight takes h one',
  'knight captures h one',
  'N h two',
  'knight to h two',
  'knight h two',
  'knight takes h two',
  'knight captures h two',
  'N h three',
  'knight to h three',
  'knight h three',
  'knight takes h three',
  'knight captures h three',
  'N h four',
  'knight to h four',
  'knight h four',
  'knight takes h four',
  'knight captures h four',
  'N h five',
  'knight to h five',
  'knight h five',
  'knight takes h five',
  'knight captures h five',
  'N h six',
  'knight to h six',
  'knight h six',
  'knight takes h six',
  'knight captures h six',
  'N h seven',
  'knight to h seven',
  'knight h seven',
  'knight takes h seven',
  'knight captures h seven',
  'N h eight',
  'knight to h eight',
  'knight h eight',
  'knight takes h eight',
  'knight captures h eight',
  'B a one',
  'bishop to a one',
  'bishop a one',
  'bishop takes a one',
  'bishop captures a one',
  'B a two',
  'bishop to a two',
  'bishop a two',
  'bishop takes a two',
  'bishop captures a two',
  'B a three',
  'bishop to a three',
  'bishop a three',
  'bishop takes a three',
  'bishop captures a three',
  'B a four',
  'bishop to a four',
  'bishop a four',
  'bishop takes a four',
  'bishop captures a four',
  'B a five',
  'bishop to a five',
  'bishop a five',
  'bishop takes a five',
  'bishop captures a five',
  'B a six',
  'bishop to a six',
  'bishop a six',
  'bishop takes a six',
  'bishop captures a six',
  'B a seven',
  'bishop to a seven',
  'bishop a seven',
  'bishop takes a seven',
  'bishop captures a seven',
  'B a eight',
  'bishop to a eight',
  'bishop a eight',
  'bishop takes a eight',
  'bishop captures a eight',
  'B b one',
  'bishop to b one',
  'bishop b one',
  'bishop takes b one',
  'bishop captures b one',
  'B b two',
  'bishop to b two',
  'bishop b two',
  'bishop takes b two',
  'bishop captures b two',
  'B b three',
  'bishop to b three',
  'bishop b three',
  'bishop takes b three',
  'bishop captures b three',
  'B b four',
  'bishop to b four',
  'bishop b four',
  'bishop takes b four',
  'bishop captures b four',
  'B b five',
  'bishop to b five',
  'bishop b five',
  'bishop takes b five',
  'bishop captures b five',
  'B b six',
  'bishop to b six',
  'bishop b six',
  'bishop takes b six',
  'bishop captures b six',
  'B b seven',
  'bishop to b seven',
  'bishop b seven',
  'bishop takes b seven',
  'bishop captures b seven',
  'B b eight',
  'bishop to b eight',
  'bishop b eight',
  'bishop takes b eight',
  'bishop captures b eight',
  'B c one',
  'bishop to c one',
  'bishop c one',
  'bishop takes c one',
  'bishop captures c one',
  'B c two',
  'bishop to c two',
  'bishop c two',
  'bishop takes c two',
  'bishop captures c two',
  'B c three',
  'bishop to c three',
  'bishop c three',
  'bishop takes c three',
  'bishop captures c three',
  'B c four',
  'bishop to c four',
  'bishop c four',
  'bishop takes c four',
  'bishop captures c four',
  'B c five',
  'bishop to c five',
  'bishop c five',
  'bishop takes c five',
  'bishop captures c five',
  'B c six',
  'bishop to c six',
  'bishop c six',
  'bishop takes c six',
  'bishop captures c six',
  'B c seven',
  'bishop to c seven',
  'bishop c seven',
  'bishop takes c seven',
  'bishop captures c seven',
  'B c eight',
  'bishop to c eight',
  'bishop c eight',
  'bishop takes c eight',
  'bishop captures c eight',
  'B d one',
  'bishop to d one',
  'bishop d one',
  'bishop takes d one',
  'bishop captures d one',
  'B d two',
  'bishop to d two',
  'bishop d two',
  'bishop takes d two',
  'bishop captures d two',
  'B d three',
  'bishop to d three',
  'bishop d three',
  'bishop takes d three',
  'bishop captures d three',
  'B d four',
  'bishop to d four',
  'bishop d four',
  'bishop takes d four',
  'bishop captures d four',
  'B d five',
  'bishop to d five',
  'bishop d five',
  'bishop takes d five',
  'bishop captures d five',
  'B d six',
  'bishop to d six',
  'bishop d six',
  'bishop takes d six',
  'bishop captures d six',
  'B d seven',
  'bishop to d seven',
  'bishop d seven',
  'bishop takes d seven',
  'bishop captures d seven',
  'B d eight',
  'bishop to d eight',
  'bishop d eight',
  'bishop takes d eight',
  'bishop captures d eight',
  'B e one',
  'bishop to e one',
  'bishop e one',
  'bishop takes e one',
  'bishop captures e one',
  'B e two',
  'bishop to e two',
  'bishop e two',
  'bishop takes e two',
  'bishop captures e two',
  'B e three',
  'bishop to e three',
  'bishop e three',
  'bishop takes e three',
  'bishop captures e three',
  'B e four',
  'bishop to e four',
  'bishop e four',
  'bishop takes e four',
  'bishop captures e four',
  'B e five',
  'bishop to e five',
  'bishop e five',
  'bishop takes e five',
  'bishop captures e five',
  'B e six',
  'bishop to e six',
  'bishop e six',
  'bishop takes e six',
  'bishop captures e six',
  'B e seven',
  'bishop to e seven',
  'bishop e seven',
  'bishop takes e seven',
  'bishop captures e seven',
  'B e eight',
  'bishop to e eight',
  'bishop e eight',
  'bishop takes e eight',
  'bishop captures e eight',
  'B f one',
  'bishop to f one',
  'bishop f one',
  'bishop takes f one',
  'bishop captures f one',
  'B f two',
  'bishop to f two',
  'bishop f two',
  'bishop takes f two',
  'bishop captures f two',
  'B f three',
  'bishop to f three',
  'bishop f three',
  'bishop takes f three',
  'bishop captures f three',
  'B f four',
  'bishop to f four',
  'bishop f four',
  'bishop takes f four',
  'bishop captures f four',
  'B f five',
  'bishop to f five',
  'bishop f five',
  'bishop takes f five',
  'bishop captures f five',
  'B f six',
  'bishop to f six',
  'bishop f six',
  'bishop takes f six',
  'bishop captures f six',
  'B f seven',
  'bishop to f seven',
  'bishop f seven',
  'bishop takes f seven',
  'bishop captures f seven',
  'B f eight',
  'bishop to f eight',
  'bishop f eight',
  'bishop takes f eight',
  'bishop captures f eight',
  'B g one',
  'bishop to g one',
  'bishop g one',
  'bishop takes g one',
  'bishop captures g one',
  'B g two',
  'bishop to g two',
  'bishop g two',
  'bishop takes g two',
  'bishop captures g two',
  'B g three',
  'bishop to g three',
  'bishop g three',
  'bishop takes g three',
  'bishop captures g three',
  'B g four',
  'bishop to g four',
  'bishop g four',
  'bishop takes g four',
  'bishop captures g four',
  'B g five',
  'bishop to g five',
  'bishop g five',
  'bishop takes g five',
  'bishop captures g five',
  'B g six',
  'bishop to g six',
  'bishop g six',
  'bishop takes g six',
  'bishop captures g six',
  'B g seven',
  'bishop to g seven',
  'bishop g seven',
  'bishop takes g seven',
  'bishop captures g seven',
  'B g eight',
  'bishop to g eight',
  'bishop g eight',
  'bishop takes g eight',
  'bishop captures g eight',
  'B h one',
  'bishop to h one',
  'bishop h one',
  'bishop takes h one',
  'bishop captures h one',
  'B h two',
  'bishop to h two',
  'bishop h two',
  'bishop takes h two',
  'bishop captures h two',
  'B h three',
  'bishop to h three',
  'bishop h three',
  'bishop takes h three',
  'bishop captures h three',
  'B h four',
  'bishop to h four',
  'bishop h four',
  'bishop takes h four',
  'bishop captures h four',
  'B h five',
  'bishop to h five',
  'bishop h five',
  'bishop takes h five',
  'bishop captures h five',
  'B h six',
  'bishop to h six',
  'bishop h six',
  'bishop takes h six',
  'bishop captures h six',
  'B h seven',
  'bishop to h seven',
  'bishop h seven',
  'bishop takes h seven',
  'bishop captures h seven',
  'B h eight',
  'bishop to h eight',
  'bishop h eight',
  'bishop takes h eight',
  'bishop captures h eight',
  'R a one',
  'rook to a one',
  'rook a one',
  'rook takes a one',
  'rook captures a one',
  'R a two',
  'rook to a two',
  'rook a two',
  'rook takes a two',
  'rook captures a two',
  'R a three',
  'rook to a three',
  'rook a three',
  'rook takes a three',
  'rook captures a three',
  'R a four',
  'rook to a four',
  'rook a four',
  'rook takes a four',
  'rook captures a four',
  'R a five',
  'rook to a five',
  'rook a five',
  'rook takes a five',
  'rook captures a five',
  'R a six',
  'rook to a six',
  'rook a six',
  'rook takes a six',
  'rook captures a six',
  'R a seven',
  'rook to a seven',
  'rook a seven',
  'rook takes a seven',
  'rook captures a seven',
  'R a eight',
  'rook to a eight',
  'rook a eight',
  'rook takes a eight',
  'rook captures a eight',
  'R b one',
  'rook to b one',
  'rook b one',
  'rook takes b one',
  'rook captures b one',
  'R b two',
  'rook to b two',
  'rook b two',
  'rook takes b two',
  'rook captures b two',
  'R b three',
  'rook to b three',
  'rook b three',
  'rook takes b three',
  'rook captures b three',
  'R b four',
  'rook to b four',
  'rook b four',
  'rook takes b four',
  'rook captures b four',
  'R b five',
  'rook to b five',
  'rook b five',
  'rook takes b five',
  'rook captures b five',
  'R b six',
  'rook to b six',
  'rook b six',
  'rook takes b six',
  'rook captures b six',
  'R b seven',
  'rook to b seven',
  'rook b seven',
  'rook takes b seven',
  'rook captures b seven',
  'R b eight',
  'rook to b eight',
  'rook b eight',
  'rook takes b eight',
  'rook captures b eight',
  'R c one',
  'rook to c one',
  'rook c one',
  'rook takes c one',
  'rook captures c one',
  'R c two',
  'rook to c two',
  'rook c two',
  'rook takes c two',
  'rook captures c two',
  'R c three',
  'rook to c three',
  'rook c three',
  'rook takes c three',
  'rook captures c three',
  'R c four',
  'rook to c four',
  'rook c four',
  'rook takes c four',
  'rook captures c four',
  'R c five',
  'rook to c five',
  'rook c five',
  'rook takes c five',
  'rook captures c five',
  'R c six',
  'rook to c six',
  'rook c six',
  'rook takes c six',
  'rook captures c six',
  'R c seven',
  'rook to c seven',
  'rook c seven',
  'rook takes c seven',
  'rook captures c seven',
  'R c eight',
  'rook to c eight',
  'rook c eight',
  'rook takes c eight',
  'rook captures c eight',
  'R d one',
  'rook to d one',
  'rook d one',
  'rook takes d one',
  'rook captures d one',
  'R d two',
  'rook to d two',
  'rook d two',
  'rook takes d two',
  'rook captures d two',
  'R d three',
  'rook to d three',
  'rook d three',
  'rook takes d three',
  'rook captures d three',
  'R d four',
  'rook to d four',
  'rook d four',
  'rook takes d four',
  'rook captures d four',
  'R d five',
  'rook to d five',
  'rook d five',
  'rook takes d five',
  'rook captures d five',
  'R d six',
  'rook to d six',
  'rook d six',
  'rook takes d six',
  'rook captures d six',
  'R d seven',
  'rook to d seven',
  'rook d seven',
  'rook takes d seven',
  'rook captures d seven',
  'R d eight',
  'rook to d eight',
  'rook d eight',
  'rook takes d eight',
  'rook captures d eight',
  'R e one',
  'rook to e one',
  'rook e one',
  'rook takes e one',
  'rook captures e one',
  'R e two',
  'rook to e two',
  'rook e two',
  'rook takes e two',
  'rook captures e two',
  'R e three',
  'rook to e three',
  'rook e three',
  'rook takes e three',
  'rook captures e three',
  'R e four',
  'rook to e four',
  'rook e four',
  'rook takes e four',
  'rook captures e four',
  'R e five',
  'rook to e five',
  'rook e five',
  'rook takes e five',
  'rook captures e five',
  'R e six',
  'rook to e six',
  'rook e six',
  'rook takes e six',
  'rook captures e six',
  'R e seven',
  'rook to e seven',
  'rook e seven',
  'rook takes e seven',
  'rook captures e seven',
  'R e eight',
  'rook to e eight',
  'rook e eight',
  'rook takes e eight',
  'rook captures e eight',
  'R f one',
  'rook to f one',
  'rook f one',
  'rook takes f one',
  'rook captures f one',
  'R f two',
  'rook to f two',
  'rook f two',
  'rook takes f two',
  'rook captures f two',
  'R f three',
  'rook to f three',
  'rook f three',
  'rook takes f three',
  'rook captures f three',
  'R f four',
  'rook to f four',
  'rook f four',
  'rook takes f four',
  'rook captures f four',
  'R f five',
  'rook to f five',
  'rook f five',
  'rook takes f five',
  'rook captures f five',
  'R f six',
  'rook to f six',
  'rook f six',
  'rook takes f six',
  'rook captures f six',
  'R f seven',
  'rook to f seven',
  'rook f seven',
  'rook takes f seven',
  'rook captures f seven',
  'R f eight',
  'rook to f eight',
  'rook f eight',
  'rook takes f eight',
  'rook captures f eight',
  'R g one',
  'rook to g one',
  'rook g one',
  'rook takes g one',
  'rook captures g one',
  'R g two',
  'rook to g two',
  'rook g two',
  'rook takes g two',
  'rook captures g two',
  'R g three',
  'rook to g three',
  'rook g three',
  'rook takes g three',
  'rook captures g three',
  'R g four',
  'rook to g four',
  'rook g four',
  'rook takes g four',
  'rook captures g four',
  'R g five',
  'rook to g five',
  'rook g five',
  'rook takes g five',
  'rook captures g five',
  'R g six',
  'rook to g six',
  'rook g six',
  'rook takes g six',
  'rook captures g six',
  'R g seven',
  'rook to g seven',
  'rook g seven',
  'rook takes g seven',
  'rook captures g seven',
  'R g eight',
  'rook to g eight',
  'rook g eight',
  'rook takes g eight',
  'rook captures g eight',
  'R h one',
  'rook to h one',
  'rook h one',
  'rook takes h one',
  'rook captures h one',
  'R h two',
  'rook to h two',
  'rook h two',
  'rook takes h two',
  'rook captures h two',
  'R h three',
  'rook to h three',
  'rook h three',
  'rook takes h three',
  'rook captures h three',
  'R h four',
  'rook to h four',
  'rook h four',
  'rook takes h four',
  'rook captures h four',
  'R h five',
  'rook to h five',
  'rook h five',
  'rook takes h five',
  'rook captures h five',
  'R h six',
  'rook to h six',
  'rook h six',
  'rook takes h six',
  'rook captures h six',
  'R h seven',
  'rook to h seven',
  'rook h seven',
  'rook takes h seven',
  'rook captures h seven',
  'R h eight',
  'rook to h eight',
  'rook h eight',
  'rook takes h eight',
  'rook captures h eight',
  'Q a one',
  'queen to a one',
  'queen a one',
  'queen takes a one',
  'queen captures a one',
  'Q a two',
  'queen to a two',
  'queen a two',
  'queen takes a two',
  'queen captures a two',
  'Q a three',
  'queen to a three',
  'queen a three',
  'queen takes a three',
  'queen captures a three',
  'Q a four',
  'queen to a four',
  'queen a four',
  'queen takes a four',
  'queen captures a four',
  'Q a five',
  'queen to a five',
  'queen a five',
  'queen takes a five',
  'queen captures a five',
  'Q a six',
  'queen to a six',
  'queen a six',
  'queen takes a six',
  'queen captures a six',
  'Q a seven',
  'queen to a seven',
  'queen a seven',
  'queen takes a seven',
  'queen captures a seven',
  'Q a eight',
  'queen to a eight',
  'queen a eight',
  'queen takes a eight',
  'queen captures a eight',
  'Q b one',
  'queen to b one',
  'queen b one',
  'queen takes b one',
  'queen captures b one',
  'Q b two',
  'queen to b two',
  'queen b two',
  'queen takes b two',
  'queen captures b two',
  'Q b three',
  'queen to b three',
  'queen b three',
  'queen takes b three',
  'queen captures b three',
  'Q b four',
  'queen to b four',
  'queen b four',
  'queen takes b four',
  'queen captures b four',
  'Q b five',
  'queen to b five',
  'queen b five',
  'queen takes b five',
  'queen captures b five',
  'Q b six',
  'queen to b six',
  'queen b six',
  'queen takes b six',
  'queen captures b six',
  'Q b seven',
  'queen to b seven',
  'queen b seven',
  'queen takes b seven',
  'queen captures b seven',
  'Q b eight',
  'queen to b eight',
  'queen b eight',
  'queen takes b eight',
  'queen captures b eight',
  'Q c one',
  'queen to c one',
  'queen c one',
  'queen takes c one',
  'queen captures c one',
  'Q c two',
  'queen to c two',
  'queen c two',
  'queen takes c two',
  'queen captures c two',
  'Q c three',
  'queen to c three',
  'queen c three',
  'queen takes c three',
  'queen captures c three',
  'Q c four',
  'queen to c four',
  'queen c four',
  'queen takes c four',
  'queen captures c four',
  'Q c five',
  'queen to c five',
  'queen c five',
  'queen takes c five',
  'queen captures c five',
  'Q c six',
  'queen to c six',
  'queen c six',
  'queen takes c six',
  'queen captures c six',
  'Q c seven',
  'queen to c seven',
  'queen c seven',
  'queen takes c seven',
  'queen captures c seven',
  'Q c eight',
  'queen to c eight',
  'queen c eight',
  'queen takes c eight',
  'queen captures c eight',
  'Q d one',
  'queen to d one',
  'queen d one',
  'queen takes d one',
  'queen captures d one',
  'Q d two',
  'queen to d two',
  'queen d two',
  'queen takes d two',
  'queen captures d two',
  'Q d three',
  'queen to d three',
  'queen d three',
  'queen takes d three',
  'queen captures d three',
  'Q d four',
  'queen to d four',
  'queen d four',
  'queen takes d four',
  'queen captures d four',
  'Q d five',
  'queen to d five',
  'queen d five',
  'queen takes d five',
  'queen captures d five',
  'Q d six',
  'queen to d six',
  'queen d six',
  'queen takes d six',
  'queen captures d six',
  'Q d seven',
  'queen to d seven',
  'queen d seven',
  'queen takes d seven',
  'queen captures d seven',
  'Q d eight',
  'queen to d eight',
  'queen d eight',
  'queen takes d eight',
  'queen captures d eight',
  'Q e one',
  'queen to e one',
  'queen e one',
  'queen takes e one',
  'queen captures e one',
  'Q e two',
  'queen to e two',
  'queen e two',
  'queen takes e two',
  'queen captures e two',
  'Q e three',
  'queen to e three',
  'queen e three',
  'queen takes e three',
  'queen captures e three',
  'Q e four',
  'queen to e four',
  'queen e four',
  'queen takes e four',
  'queen captures e four',
  'Q e five',
  'queen to e five',
  'queen e five',
  'queen takes e five',
  'queen captures e five',
  'Q e six',
  'queen to e six',
  'queen e six',
  'queen takes e six',
  'queen captures e six',
  'Q e seven',
  'queen to e seven',
  'queen e seven',
  'queen takes e seven',
  'queen captures e seven',
  'Q e eight',
  'queen to e eight',
  'queen e eight',
  'queen takes e eight',
  'queen captures e eight',
  'Q f one',
  'queen to f one',
  'queen f one',
  'queen takes f one',
  'queen captures f one',
  'Q f two',
  'queen to f two',
  'queen f two',
  'queen takes f two',
  'queen captures f two',
  'Q f three',
  'queen to f three',
  'queen f three',
  'queen takes f three',
  'queen captures f three',
  'Q f four',
  'queen to f four',
  'queen f four',
  'queen takes f four',
  'queen captures f four',
  'Q f five',
  'queen to f five',
  'queen f five',
  'queen takes f five',
  'queen captures f five',
  'Q f six',
  'queen to f six',
  'queen f six',
  'queen takes f six',
  'queen captures f six',
  'Q f seven',
  'queen to f seven',
  'queen f seven',
  'queen takes f seven',
  'queen captures f seven',
  'Q f eight',
  'queen to f eight',
  'queen f eight',
  'queen takes f eight',
  'queen captures f eight',
  'Q g one',
  'queen to g one',
  'queen g one',
  'queen takes g one',
  'queen captures g one',
  'Q g two',
  'queen to g two',
  'queen g two',
  'queen takes g two',
  'queen captures g two',
  'Q g three',
  'queen to g three',
  'queen g three',
  'queen takes g three',
  'queen captures g three',
  'Q g four',
  'queen to g four',
  'queen g four',
  'queen takes g four',
  'queen captures g four',
  'Q g five',
  'queen to g five',
  'queen g five',
  'queen takes g five',
  'queen captures g five',
  'Q g six',
  'queen to g six',
  'queen g six',
  'queen takes g six',
  'queen captures g six',
  'Q g seven',
  'queen to g seven',
  'queen g seven',
  'queen takes g seven',
  'queen captures g seven',
  'Q g eight',
  'queen to g eight',
  'queen g eight',
  'queen takes g eight',
  'queen captures g eight',
  'Q h one',
  'queen to h one',
  'queen h one',
  'queen takes h one',
  'queen captures h one',
  'Q h two',
  'queen to h two',
  'queen h two',
  'queen takes h two',
  'queen captures h two',
  'Q h three',
  'queen to h three',
  'queen h three',
  'queen takes h three',
  'queen captures h three',
  'Q h four',
  'queen to h four',
  'queen h four',
  'queen takes h four',
  'queen captures h four',
  'Q h five',
  'queen to h five',
  'queen h five',
  'queen takes h five',
  'queen captures h five',
  'Q h six',
  'queen to h six',
  'queen h six',
  'queen takes h six',
  'queen captures h six',
  'Q h seven',
  'queen to h seven',
  'queen h seven',
  'queen takes h seven',
  'queen captures h seven',
  'Q h eight',
  'queen to h eight',
  'queen h eight',
  'queen takes h eight',
  'queen captures h eight',
  'K a one',
  'king to a one',
  'king a one',
  'king takes a one',
  'king captures a one',
  'K a two',
  'king to a two',
  'king a two',
  'king takes a two',
  'king captures a two',
  'K a three',
  'king to a three',
  'king a three',
  'king takes a three',
  'king captures a three',
  'K a four',
  'king to a four',
  'king a four',
  'king takes a four',
  'king captures a four',
  'K a five',
  'king to a five',
  'king a five',
  'king takes a five',
  'king captures a five',
  'K a six',
  'king to a six',
  'king a six',
  'king takes a six',
  'king captures a six',
  'K a seven',
  'king to a seven',
  'king a seven',
  'king takes a seven',
  'king captures a seven',
  'K a eight',
  'king to a eight',
  'king a eight',
  'king takes a eight',
  'king captures a eight',
  'K b one',
  'king to b one',
  'king b one',
  'king takes b one',
  'king captures b one',
  'K b two',
  'king to b two',
  'king b two',
  'king takes b two',
  'king captures b two',
  'K b three',
  'king to b three',
  'king b three',
  'king takes b three',
  'king captures b three',
  'K b four',
  'king to b four',
  'king b four',
  'king takes b four',
  'king captures b four',
  'K b five',
  'king to b five',
  'king b five',
  'king takes b five',
  'king captures b five',
  'K b six',
  'king to b six',
  'king b six',
  'king takes b six',
  'king captures b six',
  'K b seven',
  'king to b seven',
  'king b seven',
  'king takes b seven',
  'king captures b seven',
  'K b eight',
  'king to b eight',
  'king b eight',
  'king takes b eight',
  'king captures b eight',
  'K c one',
  'king to c one',
  'king c one',
  'king takes c one',
  'king captures c one',
  'K c two',
  'king to c two',
  'king c two',
  'king takes c two',
  'king captures c two',
  'K c three',
  'king to c three',
  'king c three',
  'king takes c three',
  'king captures c three',
  'K c four',
  'king to c four',
  'king c four',
  'king takes c four',
  'king captures c four',
  'K c five',
  'king to c five',
  'king c five',
  'king takes c five',
  'king captures c five',
  'K c six',
  'king to c six',
  'king c six',
  'king takes c six',
  'king captures c six',
  'K c seven',
  'king to c seven',
  'king c seven',
  'king takes c seven',
  'king captures c seven',
  'K c eight',
  'king to c eight',
  'king c eight',
  'king takes c eight',
  'king captures c eight',
  'K d one',
  'king to d one',
  'king d one',
  'king takes d one',
  'king captures d one',
  'K d two',
  'king to d two',
  'king d two',
  'king takes d two',
  'king captures d two',
  'K d three',
  'king to d three',
  'king d three',
  'king takes d three',
  'king captures d three',
  'K d four',
  'king to d four',
  'king d four',
  'king takes d four',
  'king captures d four',
  'K d five',
  'king to d five',
  'king d five',
  'king takes d five',
  'king captures d five',
  'K d six',
  'king to d six',
  'king d six',
  'king takes d six',
  'king captures d six',
  'K d seven',
  'king to d seven',
  'king d seven',
  'king takes d seven',
  'king captures d seven',
  'K d eight',
  'king to d eight',
  'king d eight',
  'king takes d eight',
  'king captures d eight',
  'K e one',
  'king to e one',
  'king e one',
  'king takes e one',
  'king captures e one',
  'K e two',
  'king to e two',
  'king e two',
  'king takes e two',
  'king captures e two',
  'K e three',
  'king to e three',
  'king e three',
  'king takes e three',
  'king captures e three',
  'K e four',
  'king to e four',
  'king e four',
  'king takes e four',
  'king captures e four',
  'K e five',
  'king to e five',
  'king e five',
  'king takes e five',
  'king captures e five',
  'K e six',
  'king to e six',
  'king e six',
  'king takes e six',
  'king captures e six',
  'K e seven',
  'king to e seven',
  'king e seven',
  'king takes e seven',
  'king captures e seven',
  'K e eight',
  'king to e eight',
  'king e eight',
  'king takes e eight',
  'king captures e eight',
  'K f one',
  'king to f one',
  'king f one',
  'king takes f one',
  'king captures f one',
  'K f two',
  'king to f two',
  'king f two',
  'king takes f two',
  'king captures f two',
  'K f three',
  'king to f three',
  'king f three',
  'king takes f three',
  'king captures f three',
  'K f four',
  'king to f four',
  'king f four',
  'king takes f four',
  'king captures f four',
  'K f five',
  'king to f five',
  'king f five',
  'king takes f five',
  'king captures f five',
  'K f six',
  'king to f six',
  'king f six',
  'king takes f six',
  'king captures f six',
  'K f seven',
  'king to f seven',
  'king f seven',
  'king takes f seven',
  'king captures f seven',
  'K f eight',
  'king to f eight',
  'king f eight',
  'king takes f eight',
  'king captures f eight',
  'K g one',
  'king to g one',
  'king g one',
  'king takes g one',
  'king captures g one',
  'K g two',
  'king to g two',
  'king g two',
  'king takes g two',
  'king captures g two',
  'K g three',
  'king to g three',
  'king g three',
  'king takes g three',
  'king captures g three',
  'K g four',
  'king to g four',
  'king g four',
  'king takes g four',
  'king captures g four',
  'K g five',
  'king to g five',
  'king g five',
  'king takes g five',
  'king captures g five',
  'K g six',
  'king to g six',
  'king g six',
  'king takes g six',
  'king captures g six',
  'K g seven',
  'king to g seven',
  'king g seven',
  'king takes g seven',
  'king captures g seven',
  'K g eight',
  'king to g eight',
  'king g eight',
  'king takes g eight',
  'king captures g eight',
  'K h one',
  'king to h one',
  'king h one',
  'king takes h one',
  'king captures h one',
  'K h two',
  'king to h two',
  'king h two',
  'king takes h two',
  'king captures h two',
  'K h three',
  'king to h three',
  'king h three',
  'king takes h three',
  'king captures h three',
  'K h four',
  'king to h four',
  'king h four',
  'king takes h four',
  'king captures h four',
  'K h five',
  'king to h five',
  'king h five',
  'king takes h five',
  'king captures h five',
  'K h six',
  'king to h six',
  'king h six',
  'king takes h six',
  'king captures h six',
  'K h seven',
  'king to h seven',
  'king h seven',
  'king takes h seven',
  'king captures h seven',
  'K h eight',
  'king to h eight',
  'king h eight',
  'king takes h eight',
  'king captures h eight',
  'a takes b one',
  'a takes c one',
  'a takes d one',
  'a takes e one',
  'a takes f one',
  'a takes g one',
  'a takes h one',
  'a takes b two',
  'a takes c two',
  'a takes d two',
  'a takes e two',
  'a takes f two',
  'a takes g two',
  'a takes h two',
  'a takes b three',
  'a takes c three',
  'a takes d three',
  'a takes e three',
  'a takes f three',
  'a takes g three',
  'a takes h three',
  'a takes b four',
  'a takes c four',
  'a takes d four',
  'a takes e four',
  'a takes f four',
  'a takes g four',
  'a takes h four',
  'a takes b five',
  'a takes c five',
  'a takes d five',
  'a takes e five',
  'a takes f five',
  'a takes g five',
  'a takes h five',
  'a takes b six',
  'a takes c six',
  'a takes d six',
  'a takes e six',
  'a takes f six',
  'a takes g six',
  'a takes h six',
  'a takes b seven',
  'a takes c seven',
  'a takes d seven',
  'a takes e seven',
  'a takes f seven',
  'a takes g seven',
  'a takes h seven',
  'a takes b eight',
  'a takes c eight',
  'a takes d eight',
  'a takes e eight',
  'a takes f eight',
  'a takes g eight',
  'a takes h eight',
  'b takes a one',
  'b takes c one',
  'b takes d one',
  'b takes e one',
  'b takes f one',
  'b takes g one',
  'b takes h one',
  'b takes a two',
  'b takes c two',
  'b takes d two',
  'b takes e two',
  'b takes f two',
  'b takes g two',
  'b takes h two',
  'b takes a three',
  'b takes c three',
  'b takes d three',
  'b takes e three',
  'b takes f three',
  'b takes g three',
  'b takes h three',
  'b takes a four',
  'b takes c four',
  'b takes d four',
  'b takes e four',
  'b takes f four',
  'b takes g four',
  'b takes h four',
  'b takes a five',
  'b takes c five',
  'b takes d five',
  'b takes e five',
  'b takes f five',
  'b takes g five',
  'b takes h five',
  'b takes a six',
  'b takes c six',
  'b takes d six',
  'b takes e six',
  'b takes f six',
  'b takes g six',
  'b takes h six',
  'b takes a seven',
  'b takes c seven',
  'b takes d seven',
  'b takes e seven',
  'b takes f seven',
  'b takes g seven',
  'b takes h seven',
  'b takes a eight',
  'b takes c eight',
  'b takes d eight',
  'b takes e eight',
  'b takes f eight',
  'b takes g eight',
  'b takes h eight',
  'c takes a one',
  'c takes b one',
  'c takes d one',
  'c takes e one',
  'c takes f one',
  'c takes g one',
  'c takes h one',
  'c takes a two',
  'c takes b two',
  'c takes d two',
  'c takes e two',
  'c takes f two',
  'c takes g two',
  'c takes h two',
  'c takes a three',
  'c takes b three',
  'c takes d three',
  'c takes e three',
  'c takes f three',
  'c takes g three',
  'c takes h three',
  'c takes a four',
  'c takes b four',
  'c takes d four',
  'c takes e four',
  'c takes f four',
  'c takes g four',
  'c takes h four',
  'c takes a five',
  'c takes b five',
  'c takes d five',
  'c takes e five',
  'c takes f five',
  'c takes g five',
  'c takes h five',
  'c takes a six',
  'c takes b six',
  'c takes d six',
  'c takes e six',
  'c takes f six',
  'c takes g six',
  'c takes h six',
  'c takes a seven',
  'c takes b seven',
  'c takes d seven',
  'c takes e seven',
  'c takes f seven',
  'c takes g seven',
  'c takes h seven',
  'c takes a eight',
  'c takes b eight',
  'c takes d eight',
  'c takes e eight',
  'c takes f eight',
  'c takes g eight',
  'c takes h eight',
  'd takes a one',
  'd takes b one',
  'd takes c one',
  'd takes e one',
  'd takes f one',
  'd takes g one',
  'd takes h one',
  'd takes a two',
  'd takes b two',
  'd takes c two',
  'd takes e two',
  'd takes f two',
  'd takes g two',
  'd takes h two',
  'd takes a three',
  'd takes b three',
  'd takes c three',
  'd takes e three',
  'd takes f three',
  'd takes g three',
  'd takes h three',
  'd takes a four',
  'd takes b four',
  'd takes c four',
  'd takes e four',
  'd takes f four',
  'd takes g four',
  'd takes h four',
  'd takes a five',
  'd takes b five',
  'd takes c five',
  'd takes e five',
  'd takes f five',
  'd takes g five',
  'd takes h five',
  'd takes a six',
  'd takes b six',
  'd takes c six',
  'd takes e six',
  'd takes f six',
  'd takes g six',
  'd takes h six',
  'd takes a seven',
  'd takes b seven',
  'd takes c seven',
  'd takes e seven',
  'd takes f seven',
  'd takes g seven',
  'd takes h seven',
  'd takes a eight',
  'd takes b eight',
  'd takes c eight',
  'd takes e eight',
  'd takes f eight',
  'd takes g eight',
  'd takes h eight',
  'e takes a one',
  'e takes b one',
  'e takes c one',
  'e takes d one',
  'e takes f one',
  'e takes g one',
  'e takes h one',
  'e takes a two',
  'e takes b two',
  'e takes c two',
  'e takes d two',
  'e takes f two',
  'e takes g two',
  'e takes h two',
  'e takes a three',
  'e takes b three',
  'e takes c three',
  'e takes d three',
  'e takes f three',
  'e takes g three',
  'e takes h three',
  'e takes a four',
  'e takes b four',
  'e takes c four',
  'e takes d four',
  'e takes f four',
  'e takes g four',
  'e takes h four',
  'e takes a five',
  'e takes b five',
  'e takes c five',
  'e takes d five',
  'e takes f five',
  'e takes g five',
  'e takes h five',
  'e takes a six',
  'e takes b six',
  'e takes c six',
  'e takes d six',
  'e takes f six',
  'e takes g six',
  'e takes h six',
  'e takes a seven',
  'e takes b seven',
  'e takes c seven',
  'e takes d seven',
  'e takes f seven',
  'e takes g seven',
  'e takes h seven',
  'e takes a eight',
  'e takes b eight',
  'e takes c eight',
  'e takes d eight',
  'e takes f eight',
  'e takes g eight',
  'e takes h eight',
  'f takes a one',
  'f takes b one',
  'f takes c one',
  'f takes d one',
  'f takes e one',
  'f takes g one',
  'f takes h one',
  'f takes a two',
  'f takes b two',
  'f takes c two',
  'f takes d two',
  'f takes e two',
  'f takes g two',
  'f takes h two',
  'f takes a three',
  'f takes b three',
  'f takes c three',
  'f takes d three',
  'f takes e three',
  'f takes g three',
  'f takes h three',
  'f takes a four',
  'f takes b four',
  'f takes c four',
  'f takes d four',
  'f takes e four',
  'f takes g four',
  'f takes h four',
  'f takes a five',
  'f takes b five',
  'f takes c five',
  'f takes d five',
  'f takes e five',
  'f takes g five',
  'f takes h five',
  'f takes a six',
  'f takes b six',
  'f takes c six',
  'f takes d six',
  'f takes e six',
  'f takes g six',
  'f takes h six',
  'f takes a seven',
  'f takes b seven',
  'f takes c seven',
  'f takes d seven',
  'f takes e seven',
  'f takes g seven',
  'f takes h seven',
  'f takes a eight',
  'f takes b eight',
  'f takes c eight',
  'f takes d eight',
  'f takes e eight',
  'f takes g eight',
  'f takes h eight',
  'g takes a one',
  'g takes b one',
  'g takes c one',
  'g takes d one',
  'g takes e one',
  'g takes f one',
  'g takes h one',
  'g takes a two',
  'g takes b two',
  'g takes c two',
  'g takes d two',
  'g takes e two',
  'g takes f two',
  'g takes h two',
  'g takes a three',
  'g takes b three',
  'g takes c three',
  'g takes d three',
  'g takes e three',
  'g takes f three',
  'g takes h three',
  'g takes a four',
  'g takes b four',
  'g takes c four',
  'g takes d four',
  'g takes e four',
  'g takes f four',
  'g takes h four',
  'g takes a five',
  'g takes b five',
  'g takes c five',
  'g takes d five',
  'g takes e five',
  'g takes f five',
  'g takes h five',
  'g takes a six',
  'g takes b six',
  'g takes c six',
  'g takes d six',
  'g takes e six',
  'g takes f six',
  'g takes h six',
  'g takes a seven',
  'g takes b seven',
  'g takes c seven',
  'g takes d seven',
  'g takes e seven',
  'g takes f seven',
  'g takes h seven',
  'g takes a eight',
  'g takes b eight',
  'g takes c eight',
  'g takes d eight',
  'g takes e eight',
  'g takes f eight',
  'g takes h eight',
  'h takes a one',
  'h takes b one',
  'h takes c one',
  'h takes d one',
  'h takes e one',
  'h takes f one',
  'h takes g one',
  'h takes a two',
  'h takes b two',
  'h takes c two',
  'h takes d two',
  'h takes e two',
  'h takes f two',
  'h takes g two',
  'h takes a three',
  'h takes b three',
  'h takes c three',
  'h takes d three',
  'h takes e three',
  'h takes f three',
  'h takes g three',
  'h takes a four',
  'h takes b four',
  'h takes c four',
  'h takes d four',
  'h takes e four',
  'h takes f four',
  'h takes g four',
  'h takes a five',
  'h takes b five',
  'h takes c five',
  'h takes d five',
  'h takes e five',
  'h takes f five',
  'h takes g five',
  'h takes a six',
  'h takes b six',
  'h takes c six',
  'h takes d six',
  'h takes e six',
  'h takes f six',
  'h takes g six',
  'h takes a seven',
  'h takes b seven',
  'h takes c seven',
  'h takes d seven',
  'h takes e seven',
  'h takes f seven',
  'h takes g seven',
  'h takes a eight',
  'h takes b eight',
  'h takes c eight',
  'h takes d eight',
  'h takes e eight',
  'h takes f eight',
  'h takes g eight',
  'pawn takes a one',
  'pawn takes a two',
  'pawn takes a three',
  'pawn takes a four',
  'pawn takes a five',
  'pawn takes a six',
  'pawn takes a seven',
  'pawn takes a eight',
  'pawn takes b one',
  'pawn takes b two',
  'pawn takes b three',
  'pawn takes b four',
  'pawn takes b five',
  'pawn takes b six',
  'pawn takes b seven',
  'pawn takes b eight',
  'pawn takes c one',
  'pawn takes c two',
  'pawn takes c three',
  'pawn takes c four',
  'pawn takes c five',
  'pawn takes c six',
  'pawn takes c seven',
  'pawn takes c eight',
  'pawn takes d one',
  'pawn takes d two',
  'pawn takes d three',
  'pawn takes d four',
  'pawn takes d five',
  'pawn takes d six',
  'pawn takes d seven',
  'pawn takes d eight',
  'pawn takes e one',
  'pawn takes e two',
  'pawn takes e three',
  'pawn takes e four',
  'pawn takes e five',
  'pawn takes e six',
  'pawn takes e seven',
  'pawn takes e eight',
  'pawn takes f one',
  'pawn takes f two',
  'pawn takes f three',
  'pawn takes f four',
  'pawn takes f five',
  'pawn takes f six',
  'pawn takes f seven',
  'pawn takes f eight',
  'pawn takes g one',
  'pawn takes g two',
  'pawn takes g three',
  'pawn takes g four',
  'pawn takes g five',
  'pawn takes g six',
  'pawn takes g seven',
  'pawn takes g eight',
  'pawn takes h one',
  'pawn takes h two',
  'pawn takes h three',
  'pawn takes h four',
  'pawn takes h five',
  'pawn takes h six',
  'pawn takes h seven',
  'pawn takes h eight',
  'castle king side',
  'castle kingside',
  'castle queen side',
  'castle queenside',
  'king side castle',
  'kingside castle',
  'long castle',
  'queen side castle',
  'queenside castle',
  'short castle',
  'a takes b three en passant',
  'b takes a three en passant',
  'b takes c three en passant',
  'c takes b three en passant',
  'c takes d three en passant',
  'd takes c three en passant',
  'd takes e three en passant',
  'e takes d three en passant',
  'e takes f three en passant',
  'f takes e three en passant',
  'f takes g three en passant',
  'g takes f three en passant',
  'g takes h three en passant',
  'h takes g three en passant',
  'a takes b six en passant',
  'b takes a six en passant',
  'b takes c six en passant',
  'c takes b six en passant',
  'c takes d six en passant',
  'd takes c six en passant',
  'd takes e six en passant',
  'e takes d six en passant',
  'e takes f six en passant',
  'f takes e six en passant',
  'f takes g six en passant',
  'g takes f six en passant',
  'g takes h six en passant',
  'h takes g six en passant',
  'bishop promotion',
  'knight promotion',
  'queen promotion',
  'rook promotion',
  'promote to bishop',
  'promote to knight',
  'promote to queen',
  'promote to rook',
  'promotes to bishop',
  'promotes to knight',
  'promotes to queen',
  'promotes to rook',
  'promotion bishop',
  'promotion knight',
  'promotion queen',
  'promotion rook',
] as const;
