export const grammarStopWords = ['check', 'checkmate', 'mate'];

export const grammarSanMap: Record<string, string | null> = {
  // Unknown
  '[unk]': null,

  // Control actions
  undo: '_undo',
  flip: '_flip',
  resign: '_resign',

  // Atoms (not full moves)
  // ------------------------------------------------------------------------
  // File letters
  a: null,
  b: null,
  c: null,
  d: null,
  e: null,
  f: null,
  g: null,
  h: null,

  // Rank words
  one: null,
  two: null,
  three: null,
  four: null,
  five: null,
  six: null,
  seven: null,
  eight: null,

  // Keywords / connectors
  to: null,
  takes: null,
  captures: null,
  pawn: null,
  knight: null,
  n: null,
  bishop: null,
  // b: null,
  rook: null,
  r: null,
  queen: null,
  q: null,
  king: null,
  k: null,
  castle: null,
  // kingside: null,
  // queenside: null,
  side: null,
  short: null,
  long: null,
  check: null,
  checkmate: null,
  mate: null,
  draw: null,
  promote: null,
  promotes: null,
  promotion: null,
  'en passant': null,

  // Promotion phrases alone
  'bishop promotion': null,
  'knight promotion': null,
  'queen promotion': null,
  'rook promotion': null,
  'promote to bishop': null,
  'promote to knight': null,
  'promote to queen': null,
  'promote to rook': null,
  'promotes to bishop': null,
  'promotes to knight': null,
  'promotes to queen': null,
  'promotes to rook': null,
  'promotion bishop': null,
  'promotion knight': null,
  'promotion queen': null,
  'promotion rook': null,
  // ------------------------------------------------------------------------

  // Squares
  'a one': 'a1',
  'a two': 'a2',
  'a three': 'a3',
  'a four': 'a4',
  'a five': 'a5',
  'a six': 'a6',
  'a seven': 'a7',
  'a eight': 'a8',
  'b one': 'b1',
  'b two': 'b2',
  'b three': 'b3',
  'b four': 'b4',
  'b five': 'b5',
  'b six': 'b6',
  'b seven': 'b7',
  'b eight': 'b8',
  'c one': 'c1',
  'c two': 'c2',
  'c three': 'c3',
  'c four': 'c4',
  'c five': 'c5',
  'c six': 'c6',
  'c seven': 'c7',
  'c eight': 'c8',
  'd one': 'd1',
  'd two': 'd2',
  'd three': 'd3',
  'd four': 'd4',
  'd five': 'd5',
  'd six': 'd6',
  'd seven': 'd7',
  'd eight': 'd8',
  'e one': 'e1',
  'e two': 'e2',
  'e three': 'e3',
  'e four': 'e4',
  'e five': 'e5',
  'e six': 'e6',
  'e seven': 'e7',
  'e eight': 'e8',
  'f one': 'f1',
  'f two': 'f2',
  'f three': 'f3',
  'f four': 'f4',
  'f five': 'f5',
  'f six': 'f6',
  'f seven': 'f7',
  'f eight': 'f8',
  'g one': 'g1',
  'g two': 'g2',
  'g three': 'g3',
  'g four': 'g4',
  'g five': 'g5',
  'g six': 'g6',
  'g seven': 'g7',
  'g eight': 'g8',
  'h one': 'h1',
  'h two': 'h2',
  'h three': 'h3',
  'h four': 'h4',
  'h five': 'h5',
  'h six': 'h6',
  'h seven': 'h7',
  'h eight': 'h8',

  // Algebraic squares
  // Squares
  a1: 'a1',
  a2: 'a2',
  a3: 'a3',
  a4: 'a4',
  a5: 'a5',
  a6: 'a6',
  a7: 'a7',
  a8: 'a8',
  b1: 'b1',
  b2: 'b2',
  b3: 'b3',
  b4: 'b4',
  b5: 'b5',
  b6: 'b6',
  b7: 'b7',
  b8: 'b8',
  c1: 'c1',
  c2: 'c2',
  c3: 'c3',
  c4: 'c4',
  c5: 'c5',
  c6: 'c6',
  c7: 'c7',
  c8: 'c8',
  d1: 'd1',
  d2: 'd2',
  d3: 'd3',
  d4: 'd4',
  d5: 'd5',
  d6: 'd6',
  d7: 'd7',
  d8: 'd8',
  e1: 'e1',
  e2: 'e2',
  e3: 'e3',
  e4: 'e4',
  e5: 'e5',
  e6: 'e6',
  e7: 'e7',
  e8: 'e8',
  f1: 'f1',
  f2: 'f2',
  f3: 'f3',
  f4: 'f4',
  f5: 'f5',
  f6: 'f6',
  f7: 'f7',
  f8: 'f8',
  g1: 'g1',
  g2: 'g2',
  g3: 'g3',
  g4: 'g4',
  g5: 'g5',
  g6: 'g6',
  g7: 'g7',
  g8: 'g8',
  h1: 'h1',
  h2: 'h2',
  h3: 'h3',
  h4: 'h4',
  h5: 'h5',
  h6: 'h6',
  h7: 'h7',
  h8: 'h8',

  // Knight moves
  'n a one': 'Na1',
  'knight to a one': 'Na1',
  'knight a one': 'Na1',
  'knight takes a one': 'Nxa1',
  'knight captures a one': 'Nxa1',
  'n a two': 'Na2',
  'knight to a two': 'Na2',
  'knight a two': 'Na2',
  'knight takes a two': 'Nxa2',
  'knight captures a two': 'Nxa2',
  'n a three': 'Na3',
  'knight to a three': 'Na3',
  'knight a three': 'Na3',
  'knight takes a three': 'Nxa3',
  'knight captures a three': 'Nxa3',
  'n a four': 'Na4',
  'knight to a four': 'Na4',
  'knight a four': 'Na4',
  'knight takes a four': 'Nxa4',
  'knight captures a four': 'Nxa4',
  'n a five': 'Na5',
  'knight to a five': 'Na5',
  'knight a five': 'Na5',
  'knight takes a five': 'Nxa5',
  'knight captures a five': 'Nxa5',
  'n a six': 'Na6',
  'knight to a six': 'Na6',
  'knight a six': 'Na6',
  'knight takes a six': 'Nxa6',
  'knight captures a six': 'Nxa6',
  'n a seven': 'Na7',
  'knight to a seven': 'Na7',
  'knight a seven': 'Na7',
  'knight takes a seven': 'Nxa7',
  'knight captures a seven': 'Nxa7',
  'n a eight': 'Na8',
  'knight to a eight': 'Na8',
  'knight a eight': 'Na8',
  'knight takes a eight': 'Nxa8',
  'knight captures a eight': 'Nxa8',
  'n b one': 'Nb1',
  'knight to b one': 'Nb1',
  'knight b one': 'Nb1',
  'knight takes b one': 'Nxb1',
  'knight captures b one': 'Nxb1',
  'n b two': 'Nb2',
  'knight to b two': 'Nb2',
  'knight b two': 'Nb2',
  'knight takes b two': 'Nxb2',
  'knight captures b two': 'Nxb2',
  'n b three': 'Nb3',
  'knight to b three': 'Nb3',
  'knight b three': 'Nb3',
  'knight takes b three': 'Nxb3',
  'knight captures b three': 'Nxb3',
  'n b four': 'Nb4',
  'knight to b four': 'Nb4',
  'knight b four': 'Nb4',
  'knight takes b four': 'Nxb4',
  'knight captures b four': 'Nxb4',
  'n b five': 'Nb5',
  'knight to b five': 'Nb5',
  'knight b five': 'Nb5',
  'knight takes b five': 'Nxb5',
  'knight captures b five': 'Nxb5',
  'n b six': 'Nb6',
  'knight to b six': 'Nb6',
  'knight b six': 'Nb6',
  'knight takes b six': 'Nxb6',
  'knight captures b six': 'Nxb6',
  'n b seven': 'Nb7',
  'knight to b seven': 'Nb7',
  'knight b seven': 'Nb7',
  'knight takes b seven': 'Nxb7',
  'knight captures b seven': 'Nxb7',
  'n b eight': 'Nb8',
  'knight to b eight': 'Nb8',
  'knight b eight': 'Nb8',
  'knight takes b eight': 'Nxb8',
  'knight captures b eight': 'Nxb8',
  'n c one': 'Nc1',
  'knight to c one': 'Nc1',
  'knight c one': 'Nc1',
  'knight takes c one': 'Nxc1',
  'knight captures c one': 'Nxc1',
  'n c two': 'Nc2',
  'knight to c two': 'Nc2',
  'knight c two': 'Nc2',
  'knight takes c two': 'Nxc2',
  'knight captures c two': 'Nxc2',
  'n c three': 'Nc3',
  'knight to c three': 'Nc3',
  'knight c three': 'Nc3',
  'knight takes c three': 'Nxc3',
  'knight captures c three': 'Nxc3',
  'n c four': 'Nc4',
  'knight to c four': 'Nc4',
  'knight c four': 'Nc4',
  'knight takes c four': 'Nxc4',
  'knight captures c four': 'Nxc4',
  'n c five': 'Nc5',
  'knight to c five': 'Nc5',
  'knight c five': 'Nc5',
  'knight takes c five': 'Nxc5',
  'knight captures c five': 'Nxc5',
  'n c six': 'Nc6',
  'knight to c six': 'Nc6',
  'knight c six': 'Nc6',
  'knight takes c six': 'Nxc6',
  'knight captures c six': 'Nxc6',
  'n c seven': 'Nc7',
  'knight to c seven': 'Nc7',
  'knight c seven': 'Nc7',
  'knight takes c seven': 'Nxc7',
  'knight captures c seven': 'Nxc7',
  'n c eight': 'Nc8',
  'knight to c eight': 'Nc8',
  'knight c eight': 'Nc8',
  'knight takes c eight': 'Nxc8',
  'knight captures c eight': 'Nxc8',
  'n d one': 'Nd1',
  'knight to d one': 'Nd1',
  'knight d one': 'Nd1',
  'knight takes d one': 'Nxd1',
  'knight captures d one': 'Nxd1',
  'n d two': 'Nd2',
  'knight to d two': 'Nd2',
  'knight d two': 'Nd2',
  'knight takes d two': 'Nxd2',
  'knight captures d two': 'Nxd2',
  'n d three': 'Nd3',
  'knight to d three': 'Nd3',
  'knight d three': 'Nd3',
  'knight takes d three': 'Nxd3',
  'knight captures d three': 'Nxd3',
  'n d four': 'Nd4',
  'knight to d four': 'Nd4',
  'knight d four': 'Nd4',
  'knight takes d four': 'Nxd4',
  'knight captures d four': 'Nxd4',
  'n d five': 'Nd5',
  'knight to d five': 'Nd5',
  'knight d five': 'Nd5',
  'knight takes d five': 'Nxd5',
  'knight captures d five': 'Nxd5',
  'n d six': 'Nd6',
  'knight to d six': 'Nd6',
  'knight d six': 'Nd6',
  'knight takes d six': 'Nxd6',
  'knight captures d six': 'Nxd6',
  'n d seven': 'Nd7',
  'knight to d seven': 'Nd7',
  'knight d seven': 'Nd7',
  'knight takes d seven': 'Nxd7',
  'knight captures d seven': 'Nxd7',
  'n d eight': 'Nd8',
  'knight to d eight': 'Nd8',
  'knight d eight': 'Nd8',
  'knight takes d eight': 'Nxd8',
  'knight captures d eight': 'Nxd8',
  'n e one': 'Ne1',
  'knight to e one': 'Ne1',
  'knight e one': 'Ne1',
  'knight takes e one': 'Nxe1',
  'knight captures e one': 'Nxe1',
  'n e two': 'Ne2',
  'knight to e two': 'Ne2',
  'knight e two': 'Ne2',
  'knight takes e two': 'Nxe2',
  'knight captures e two': 'Nxe2',
  'n e three': 'Ne3',
  'knight to e three': 'Ne3',
  'knight e three': 'Ne3',
  'knight takes e three': 'Nxe3',
  'knight captures e three': 'Nxe3',
  'n e four': 'Ne4',
  'knight to e four': 'Ne4',
  'knight e four': 'Ne4',
  'knight takes e four': 'Nxe4',
  'knight captures e four': 'Nxe4',
  'n e five': 'Ne5',
  'knight to e five': 'Ne5',
  'knight e five': 'Ne5',
  'knight takes e five': 'Nxe5',
  'knight captures e five': 'Nxe5',
  'n e six': 'Ne6',
  'knight to e six': 'Ne6',
  'knight e six': 'Ne6',
  'knight takes e six': 'Nxe6',
  'knight captures e six': 'Nxe6',
  'n e seven': 'Ne7',
  'knight to e seven': 'Ne7',
  'knight e seven': 'Ne7',
  'knight takes e seven': 'Nxe7',
  'knight captures e seven': 'Nxe7',
  'n e eight': 'Ne8',
  'knight to e eight': 'Ne8',
  'knight e eight': 'Ne8',
  'knight takes e eight': 'Nxe8',
  'knight captures e eight': 'Nxe8',
  'n f one': 'Nf1',
  'knight to f one': 'Nf1',
  'knight f one': 'Nf1',
  'knight takes f one': 'Nxf1',
  'knight captures f one': 'Nxf1',
  'n f two': 'Nf2',
  'knight to f two': 'Nf2',
  'knight f two': 'Nf2',
  'knight takes f two': 'Nxf2',
  'knight captures f two': 'Nxf2',
  'n f three': 'Nf3',
  'knight to f three': 'Nf3',
  'knight f three': 'Nf3',
  'knight takes f three': 'Nxf3',
  'knight captures f three': 'Nxf3',
  'n f four': 'Nf4',
  'knight to f four': 'Nf4',
  'knight f four': 'Nf4',
  'knight takes f four': 'Nxf4',
  'knight captures f four': 'Nxf4',
  'n f five': 'Nf5',
  'knight to f five': 'Nf5',
  'knight f five': 'Nf5',
  'knight takes f five': 'Nxf5',
  'knight captures f five': 'Nxf5',
  'n f six': 'Nf6',
  'knight to f six': 'Nf6',
  'knight f six': 'Nf6',
  'knight takes f six': 'Nxf6',
  'knight captures f six': 'Nxf6',
  'n f seven': 'Nf7',
  'knight to f seven': 'Nf7',
  'knight f seven': 'Nf7',
  'knight takes f seven': 'Nxf7',
  'knight captures f seven': 'Nxf7',
  'n f eight': 'Nf8',
  'knight to f eight': 'Nf8',
  'knight f eight': 'Nf8',
  'knight takes f eight': 'Nxf8',
  'knight captures f eight': 'Nxf8',
  'n g one': 'Ng1',
  'knight to g one': 'Ng1',
  'knight g one': 'Ng1',
  'knight takes g one': 'Nxg1',
  'knight captures g one': 'Nxg1',
  'n g two': 'Ng2',
  'knight to g two': 'Ng2',
  'knight g two': 'Ng2',
  'knight takes g two': 'Nxg2',
  'knight captures g two': 'Nxg2',
  'n g three': 'Ng3',
  'knight to g three': 'Ng3',
  'knight g three': 'Ng3',
  'knight takes g three': 'Nxg3',
  'knight captures g three': 'Nxg3',
  'n g four': 'Ng4',
  'knight to g four': 'Ng4',
  'knight g four': 'Ng4',
  'knight takes g four': 'Nxg4',
  'knight captures g four': 'Nxg4',
  'n g five': 'Ng5',
  'knight to g five': 'Ng5',
  'knight g five': 'Ng5',
  'knight takes g five': 'Nxg5',
  'knight captures g five': 'Nxg5',
  'n g six': 'Ng6',
  'knight to g six': 'Ng6',
  'knight g six': 'Ng6',
  'knight takes g six': 'Nxg6',
  'knight captures g six': 'Nxg6',
  'n g seven': 'Ng7',
  'knight to g seven': 'Ng7',
  'knight g seven': 'Ng7',
  'knight takes g seven': 'Nxg7',
  'knight captures g seven': 'Nxg7',
  'n g eight': 'Ng8',
  'knight to g eight': 'Ng8',
  'knight g eight': 'Ng8',
  'knight takes g eight': 'Nxg8',
  'knight captures g eight': 'Nxg8',
  'n h one': 'Nh1',
  'knight to h one': 'Nh1',
  'knight h one': 'Nh1',
  'knight takes h one': 'Nxh1',
  'knight captures h one': 'Nxh1',
  'n h two': 'Nh2',
  'knight to h two': 'Nh2',
  'knight h two': 'Nh2',
  'knight takes h two': 'Nxh2',
  'knight captures h two': 'Nxh2',
  'n h three': 'Nh3',
  'knight to h three': 'Nh3',
  'knight h three': 'Nh3',
  'knight takes h three': 'Nxh3',
  'knight captures h three': 'Nxh3',
  'n h four': 'Nh4',
  'knight to h four': 'Nh4',
  'knight h four': 'Nh4',
  'knight takes h four': 'Nxh4',
  'knight captures h four': 'Nxh4',
  'n h five': 'Nh5',
  'knight to h five': 'Nh5',
  'knight h five': 'Nh5',
  'knight takes h five': 'Nxh5',
  'knight captures h five': 'Nxh5',
  'n h six': 'Nh6',
  'knight to h six': 'Nh6',
  'knight h six': 'Nh6',
  'knight takes h six': 'Nxh6',
  'knight captures h six': 'Nxh6',
  'n h seven': 'Nh7',
  'knight to h seven': 'Nh7',
  'knight h seven': 'Nh7',
  'knight takes h seven': 'Nxh7',
  'knight captures h seven': 'Nxh7',
  'n h eight': 'Nh8',
  'knight to h eight': 'Nh8',
  'knight h eight': 'Nh8',
  'knight takes h eight': 'Nxh8',
  'knight captures h eight': 'Nxh8',

  // Bishop moves
  'b a one': 'Ba1',
  'bishop to a one': 'Ba1',
  'bishop a one': 'Ba1',
  'bishop takes a one': 'Bxa1',
  'bishop captures a one': 'Bxa1',
  'b a two': 'Ba2',
  'bishop to a two': 'Ba2',
  'bishop a two': 'Ba2',
  'bishop takes a two': 'Bxa2',
  'bishop captures a two': 'Bxa2',
  'b a three': 'Ba3',
  'bishop to a three': 'Ba3',
  'bishop a three': 'Ba3',
  'bishop takes a three': 'Bxa3',
  'bishop captures a three': 'Bxa3',
  'b a four': 'Ba4',
  'bishop to a four': 'Ba4',
  'bishop a four': 'Ba4',
  'bishop takes a four': 'Bxa4',
  'bishop captures a four': 'Bxa4',
  'b a five': 'Ba5',
  'bishop to a five': 'Ba5',
  'bishop a five': 'Ba5',
  'bishop takes a five': 'Bxa5',
  'bishop captures a five': 'Bxa5',
  'b a six': 'Ba6',
  'bishop to a six': 'Ba6',
  'bishop a six': 'Ba6',
  'bishop takes a six': 'Bxa6',
  'bishop captures a six': 'Bxa6',
  'b a seven': 'Ba7',
  'bishop to a seven': 'Ba7',
  'bishop a seven': 'Ba7',
  'bishop takes a seven': 'Bxa7',
  'bishop captures a seven': 'Bxa7',
  'b a eight': 'Ba8',
  'bishop to a eight': 'Ba8',
  'bishop a eight': 'Ba8',
  'bishop takes a eight': 'Bxa8',
  'bishop captures a eight': 'Bxa8',
  'b b one': 'Bb1',
  'bishop to b one': 'Bb1',
  'bishop b one': 'Bb1',
  'bishop takes b one': 'Bxb1',
  'bishop captures b one': 'Bxb1',
  'b b two': 'Bb2',
  'bishop to b two': 'Bb2',
  'bishop b two': 'Bb2',
  'bishop takes b two': 'Bxb2',
  'bishop captures b two': 'Bxb2',
  'b b three': 'Bb3',
  'bishop to b three': 'Bb3',
  'bishop b three': 'Bb3',
  'bishop takes b three': 'Bxb3',
  'bishop captures b three': 'Bxb3',
  'b b four': 'Bb4',
  'bishop to b four': 'Bb4',
  'bishop b four': 'Bb4',
  'bishop takes b four': 'Bxb4',
  'bishop captures b four': 'Bxb4',
  'b b five': 'Bb5',
  'bishop to b five': 'Bb5',
  'bishop b five': 'Bb5',
  'bishop takes b five': 'Bxb5',
  'bishop captures b five': 'Bxb5',
  'b b six': 'Bb6',
  'bishop to b six': 'Bb6',
  'bishop b six': 'Bb6',
  'bishop takes b six': 'Bxb6',
  'bishop captures b six': 'Bxb6',
  'b b seven': 'Bb7',
  'bishop to b seven': 'Bb7',
  'bishop b seven': 'Bb7',
  'bishop takes b seven': 'Bxb7',
  'bishop captures b seven': 'Bxb7',
  'b b eight': 'Bb8',
  'bishop to b eight': 'Bb8',
  'bishop b eight': 'Bb8',
  'bishop takes b eight': 'Bxb8',
  'bishop captures b eight': 'Bxb8',
  'b c one': 'Bc1',
  'bishop to c one': 'Bc1',
  'bishop c one': 'Bc1',
  'bishop takes c one': 'Bxc1',
  'bishop captures c one': 'Bxc1',
  'b c two': 'Bc2',
  'bishop to c two': 'Bc2',
  'bishop c two': 'Bc2',
  'bishop takes c two': 'Bxc2',
  'bishop captures c two': 'Bxc2',
  'b c three': 'Bc3',
  'bishop to c three': 'Bc3',
  'bishop c three': 'Bc3',
  'bishop takes c three': 'Bxc3',
  'bishop captures c three': 'Bxc3',
  'b c four': 'Bc4',
  'bishop to c four': 'Bc4',
  'bishop c four': 'Bc4',
  'bishop takes c four': 'Bxc4',
  'bishop captures c four': 'Bxc4',
  'b c five': 'Bc5',
  'bishop to c five': 'Bc5',
  'bishop c five': 'Bc5',
  'bishop takes c five': 'Bxc5',
  'bishop captures c five': 'Bxc5',
  'b c six': 'Bc6',
  'bishop to c six': 'Bc6',
  'bishop c six': 'Bc6',
  'bishop takes c six': 'Bxc6',
  'bishop captures c six': 'Bxc6',
  'b c seven': 'Bc7',
  'bishop to c seven': 'Bc7',
  'bishop c seven': 'Bc7',
  'bishop takes c seven': 'Bxc7',
  'bishop captures c seven': 'Bxc7',
  'b c eight': 'Bc8',
  'bishop to c eight': 'Bc8',
  'bishop c eight': 'Bc8',
  'bishop takes c eight': 'Bxc8',
  'bishop captures c eight': 'Bxc8',
  'b d one': 'Bd1',
  'bishop to d one': 'Bd1',
  'bishop d one': 'Bd1',
  'bishop takes d one': 'Bxd1',
  'bishop captures d one': 'Bxd1',
  'b d two': 'Bd2',
  'bishop to d two': 'Bd2',
  'bishop d two': 'Bd2',
  'bishop takes d two': 'Bxd2',
  'bishop captures d two': 'Bxd2',
  'b d three': 'Bd3',
  'bishop to d three': 'Bd3',
  'bishop d three': 'Bd3',
  'bishop takes d three': 'Bxd3',
  'bishop captures d three': 'Bxd3',
  'b d four': 'Bd4',
  'bishop to d four': 'Bd4',
  'bishop d four': 'Bd4',
  'bishop takes d four': 'Bxd4',
  'bishop captures d four': 'Bxd4',
  'b d five': 'Bd5',
  'bishop to d five': 'Bd5',
  'bishop d five': 'Bd5',
  'bishop takes d five': 'Bxd5',
  'bishop captures d five': 'Bxd5',
  'b d six': 'Bd6',
  'bishop to d six': 'Bd6',
  'bishop d six': 'Bd6',
  'bishop takes d six': 'Bxd6',
  'bishop captures d six': 'Bxd6',
  'b d seven': 'Bd7',
  'bishop to d seven': 'Bd7',
  'bishop d seven': 'Bd7',
  'bishop takes d seven': 'Bxd7',
  'bishop captures d seven': 'Bxd7',
  'b d eight': 'Bd8',
  'bishop to d eight': 'Bd8',
  'bishop d eight': 'Bd8',
  'bishop takes d eight': 'Bxd8',
  'bishop captures d eight': 'Bxd8',
  'b e one': 'Be1',
  'bishop to e one': 'Be1',
  'bishop e one': 'Be1',
  'bishop takes e one': 'Bxe1',
  'bishop captures e one': 'Bxe1',
  'b e two': 'Be2',
  'bishop to e two': 'Be2',
  'bishop e two': 'Be2',
  'bishop takes e two': 'Bxe2',
  'bishop captures e two': 'Bxe2',
  'b e three': 'Be3',
  'bishop to e three': 'Be3',
  'bishop e three': 'Be3',
  'bishop takes e three': 'Bxe3',
  'bishop captures e three': 'Bxe3',
  'b e four': 'Be4',
  'bishop to e four': 'Be4',
  'bishop e four': 'Be4',
  'bishop takes e four': 'Bxe4',
  'bishop captures e four': 'Bxe4',
  'b e five': 'Be5',
  'bishop to e five': 'Be5',
  'bishop e five': 'Be5',
  'bishop takes e five': 'Bxe5',
  'bishop captures e five': 'Bxe5',
  'b e six': 'Be6',
  'bishop to e six': 'Be6',
  'bishop e six': 'Be6',
  'bishop takes e six': 'Bxe6',
  'bishop captures e six': 'Bxe6',
  'b e seven': 'Be7',
  'bishop to e seven': 'Be7',
  'bishop e seven': 'Be7',
  'bishop takes e seven': 'Bxe7',
  'bishop captures e seven': 'Bxe7',
  'b e eight': 'Be8',
  'bishop to e eight': 'Be8',
  'bishop e eight': 'Be8',
  'bishop takes e eight': 'Bxe8',
  'bishop captures e eight': 'Bxe8',
  'b f one': 'Bf1',
  'bishop to f one': 'Bf1',
  'bishop f one': 'Bf1',
  'bishop takes f one': 'Bxf1',
  'bishop captures f one': 'Bxf1',
  'b f two': 'Bf2',
  'bishop to f two': 'Bf2',
  'bishop f two': 'Bf2',
  'bishop takes f two': 'Bxf2',
  'bishop captures f two': 'Bxf2',
  'b f three': 'Bf3',
  'bishop to f three': 'Bf3',
  'bishop f three': 'Bf3',
  'bishop takes f three': 'Bxf3',
  'bishop captures f three': 'Bxf3',
  'b f four': 'Bf4',
  'bishop to f four': 'Bf4',
  'bishop f four': 'Bf4',
  'bishop takes f four': 'Bxf4',
  'bishop captures f four': 'Bxf4',
  'b f five': 'Bf5',
  'bishop to f five': 'Bf5',
  'bishop f five': 'Bf5',
  'bishop takes f five': 'Bxf5',
  'bishop captures f five': 'Bxf5',
  'b f six': 'Bf6',
  'bishop to f six': 'Bf6',
  'bishop f six': 'Bf6',
  'bishop takes f six': 'Bxf6',
  'bishop captures f six': 'Bxf6',
  'b f seven': 'Bf7',
  'bishop to f seven': 'Bf7',
  'bishop f seven': 'Bf7',
  'bishop takes f seven': 'Bxf7',
  'bishop captures f seven': 'Bxf7',
  'b f eight': 'Bf8',
  'bishop to f eight': 'Bf8',
  'bishop f eight': 'Bf8',
  'bishop takes f eight': 'Bxf8',
  'bishop captures f eight': 'Bxf8',
  'b g one': 'Bg1',
  'bishop to g one': 'Bg1',
  'bishop g one': 'Bg1',
  'bishop takes g one': 'Bxg1',
  'bishop captures g one': 'Bxg1',
  'b g two': 'Bg2',
  'bishop to g two': 'Bg2',
  'bishop g two': 'Bg2',
  'bishop takes g two': 'Bxg2',
  'bishop captures g two': 'Bxg2',
  'b g three': 'Bg3',
  'bishop to g three': 'Bg3',
  'bishop g three': 'Bg3',
  'bishop takes g three': 'Bxg3',
  'bishop captures g three': 'Bxg3',
  'b g four': 'Bg4',
  'bishop to g four': 'Bg4',
  'bishop g four': 'Bg4',
  'bishop takes g four': 'Bxg4',
  'bishop captures g four': 'Bxg4',
  'b g five': 'Bg5',
  'bishop to g five': 'Bg5',
  'bishop g five': 'Bg5',
  'bishop takes g five': 'Bxg5',
  'bishop captures g five': 'Bxg5',
  'b g six': 'Bg6',
  'bishop to g six': 'Bg6',
  'bishop g six': 'Bg6',
  'bishop takes g six': 'Bxg6',
  'bishop captures g six': 'Bxg6',
  'b g seven': 'Bg7',
  'bishop to g seven': 'Bg7',
  'bishop g seven': 'Bg7',
  'bishop takes g seven': 'Bxg7',
  'bishop captures g seven': 'Bxg7',
  'b g eight': 'Bg8',
  'bishop to g eight': 'Bg8',
  'bishop g eight': 'Bg8',
  'bishop takes g eight': 'Bxg8',
  'bishop captures g eight': 'Bxg8',
  'b h one': 'Bh1',
  'bishop to h one': 'Bh1',
  'bishop h one': 'Bh1',
  'bishop takes h one': 'Bxh1',
  'bishop captures h one': 'Bxh1',
  'b h two': 'Bh2',
  'bishop to h two': 'Bh2',
  'bishop h two': 'Bh2',
  'bishop takes h two': 'Bxh2',
  'bishop captures h two': 'Bxh2',
  'b h three': 'Bh3',
  'bishop to h three': 'Bh3',
  'bishop h three': 'Bh3',
  'bishop takes h three': 'Bxh3',
  'bishop captures h three': 'Bxh3',
  'b h four': 'Bh4',
  'bishop to h four': 'Bh4',
  'bishop h four': 'Bh4',
  'bishop takes h four': 'Bxh4',
  'bishop captures h four': 'Bxh4',
  'b h five': 'Bh5',
  'bishop to h five': 'Bh5',
  'bishop h five': 'Bh5',
  'bishop takes h five': 'Bxh5',
  'bishop captures h five': 'Bxh5',
  'b h six': 'Bh6',
  'bishop to h six': 'Bh6',
  'bishop h six': 'Bh6',
  'bishop takes h six': 'Bxh6',
  'bishop captures h six': 'Bxh6',
  'b h seven': 'Bh7',
  'bishop to h seven': 'Bh7',
  'bishop h seven': 'Bh7',
  'bishop takes h seven': 'Bxh7',
  'bishop captures h seven': 'Bxh7',
  'b h eight': 'Bh8',
  'bishop to h eight': 'Bh8',
  'bishop h eight': 'Bh8',
  'bishop takes h eight': 'Bxh8',
  'bishop captures h eight': 'Bxh8',

  // Rook moves
  'r a one': 'Ra1',
  'rook to a one': 'Ra1',
  'rook a one': 'Ra1',
  'rook takes a one': 'Rxa1',
  'rook captures a one': 'Rxa1',
  'r a two': 'Ra2',
  'rook to a two': 'Ra2',
  'rook a two': 'Ra2',
  'rook takes a two': 'Rxa2',
  'rook captures a two': 'Rxa2',
  'r a three': 'Ra3',
  'rook to a three': 'Ra3',
  'rook a three': 'Ra3',
  'rook takes a three': 'Rxa3',
  'rook captures a three': 'Rxa3',
  'r a four': 'Ra4',
  'rook to a four': 'Ra4',
  'rook a four': 'Ra4',
  'rook takes a four': 'Rxa4',
  'rook captures a four': 'Rxa4',
  'r a five': 'Ra5',
  'rook to a five': 'Ra5',
  'rook a five': 'Ra5',
  'rook takes a five': 'Rxa5',
  'rook captures a five': 'Rxa5',
  'r a six': 'Ra6',
  'rook to a six': 'Ra6',
  'rook a six': 'Ra6',
  'rook takes a six': 'Rxa6',
  'rook captures a six': 'Rxa6',
  'r a seven': 'Ra7',
  'rook to a seven': 'Ra7',
  'rook a seven': 'Ra7',
  'rook takes a seven': 'Rxa7',
  'rook captures a seven': 'Rxa7',
  'r a eight': 'Ra8',
  'rook to a eight': 'Ra8',
  'rook a eight': 'Ra8',
  'rook takes a eight': 'Rxa8',
  'rook captures a eight': 'Rxa8',
  'r b one': 'Rb1',
  'rook to b one': 'Rb1',
  'rook b one': 'Rb1',
  'rook takes b one': 'Rxb1',
  'rook captures b one': 'Rxb1',
  'r b two': 'Rb2',
  'rook to b two': 'Rb2',
  'rook b two': 'Rb2',
  'rook takes b two': 'Rxb2',
  'rook captures b two': 'Rxb2',
  'r b three': 'Rb3',
  'rook to b three': 'Rb3',
  'rook b three': 'Rb3',
  'rook takes b three': 'Rxb3',
  'rook captures b three': 'Rxb3',
  'r b four': 'Rb4',
  'rook to b four': 'Rb4',
  'rook b four': 'Rb4',
  'rook takes b four': 'Rxb4',
  'rook captures b four': 'Rxb4',
  'r b five': 'Rb5',
  'rook to b five': 'Rb5',
  'rook b five': 'Rb5',
  'rook takes b five': 'Rxb5',
  'rook captures b five': 'Rxb5',
  'r b six': 'Rb6',
  'rook to b six': 'Rb6',
  'rook b six': 'Rb6',
  'rook takes b six': 'Rxb6',
  'rook captures b six': 'Rxb6',
  'r b seven': 'Rb7',
  'rook to b seven': 'Rb7',
  'rook b seven': 'Rb7',
  'rook takes b seven': 'Rxb7',
  'rook captures b seven': 'Rxb7',
  'r b eight': 'Rb8',
  'rook to b eight': 'Rb8',
  'rook b eight': 'Rb8',
  'rook takes b eight': 'Rxb8',
  'rook captures b eight': 'Rxb8',
  'r c one': 'Rc1',
  'rook to c one': 'Rc1',
  'rook c one': 'Rc1',
  'rook takes c one': 'Rxc1',
  'rook captures c one': 'Rxc1',
  'r c two': 'Rc2',
  'rook to c two': 'Rc2',
  'rook c two': 'Rc2',
  'rook takes c two': 'Rxc2',
  'rook captures c two': 'Rxc2',
  'r c three': 'Rc3',
  'rook to c three': 'Rc3',
  'rook c three': 'Rc3',
  'rook takes c three': 'Rxc3',
  'rook captures c three': 'Rxc3',
  'r c four': 'Rc4',
  'rook to c four': 'Rc4',
  'rook c four': 'Rc4',
  'rook takes c four': 'Rxc4',
  'rook captures c four': 'Rxc4',
  'r c five': 'Rc5',
  'rook to c five': 'Rc5',
  'rook c five': 'Rc5',
  'rook takes c five': 'Rxc5',
  'rook captures c five': 'Rxc5',
  'r c six': 'Rc6',
  'rook to c six': 'Rc6',
  'rook c six': 'Rc6',
  'rook takes c six': 'Rxc6',
  'rook captures c six': 'Rxc6',
  'r c seven': 'Rc7',
  'rook to c seven': 'Rc7',
  'rook c seven': 'Rc7',
  'rook takes c seven': 'Rxc7',
  'rook captures c seven': 'Rxc7',
  'r c eight': 'Rc8',
  'rook to c eight': 'Rc8',
  'rook c eight': 'Rc8',
  'rook takes c eight': 'Rxc8',
  'rook captures c eight': 'Rxc8',
  'r d one': 'Rd1',
  'rook to d one': 'Rd1',
  'rook d one': 'Rd1',
  'rook takes d one': 'Rxd1',
  'rook captures d one': 'Rxd1',
  'r d two': 'Rd2',
  'rook to d two': 'Rd2',
  'rook d two': 'Rd2',
  'rook takes d two': 'Rxd2',
  'rook captures d two': 'Rxd2',
  'r d three': 'Rd3',
  'rook to d three': 'Rd3',
  'rook d three': 'Rd3',
  'rook takes d three': 'Rxd3',
  'rook captures d three': 'Rxd3',
  'r d four': 'Rd4',
  'rook to d four': 'Rd4',
  'rook d four': 'Rd4',
  'rook takes d four': 'Rxd4',
  'rook captures d four': 'Rxd4',
  'r d five': 'Rd5',
  'rook to d five': 'Rd5',
  'rook d five': 'Rd5',
  'rook takes d five': 'Rxd5',
  'rook captures d five': 'Rxd5',
  'r d six': 'Rd6',
  'rook to d six': 'Rd6',
  'rook d six': 'Rd6',
  'rook takes d six': 'Rxd6',
  'rook captures d six': 'Rxd6',
  'r d seven': 'Rd7',
  'rook to d seven': 'Rd7',
  'rook d seven': 'Rd7',
  'rook takes d seven': 'Rxd7',
  'rook captures d seven': 'Rxd7',
  'r d eight': 'Rd8',
  'rook to d eight': 'Rd8',
  'rook d eight': 'Rd8',
  'rook takes d eight': 'Rxd8',
  'rook captures d eight': 'Rxd8',
  'r e one': 'Re1',
  'rook to e one': 'Re1',
  'rook e one': 'Re1',
  'rook takes e one': 'Rxe1',
  'rook captures e one': 'Rxe1',
  'r e two': 'Re2',
  'rook to e two': 'Re2',
  'rook e two': 'Re2',
  'rook takes e two': 'Rxe2',
  'rook captures e two': 'Rxe2',
  'r e three': 'Re3',
  'rook to e three': 'Re3',
  'rook e three': 'Re3',
  'rook takes e three': 'Rxe3',
  'rook captures e three': 'Rxe3',
  'r e four': 'Re4',
  'rook to e four': 'Re4',
  'rook e four': 'Re4',
  'rook takes e four': 'Rxe4',
  'rook captures e four': 'Rxe4',
  'r e five': 'Re5',
  'rook to e five': 'Re5',
  'rook e five': 'Re5',
  'rook takes e five': 'Rxe5',
  'rook captures e five': 'Rxe5',
  'r e six': 'Re6',
  'rook to e six': 'Re6',
  'rook e six': 'Re6',
  'rook takes e six': 'Rxe6',
  'rook captures e six': 'Rxe6',
  'r e seven': 'Re7',
  'rook to e seven': 'Re7',
  'rook e seven': 'Re7',
  'rook takes e seven': 'Rxe7',
  'rook captures e seven': 'Rxe7',
  'r e eight': 'Re8',
  'rook to e eight': 'Re8',
  'rook e eight': 'Re8',
  'rook takes e eight': 'Rxe8',
  'rook captures e eight': 'Rxe8',
  'r f one': 'Rf1',
  'rook to f one': 'Rf1',
  'rook f one': 'Rf1',
  'rook takes f one': 'Rxf1',
  'rook captures f one': 'Rxf1',
  'r f two': 'Rf2',
  'rook to f two': 'Rf2',
  'rook f two': 'Rf2',
  'rook takes f two': 'Rxf2',
  'rook captures f two': 'Rxf2',
  'r f three': 'Rf3',
  'rook to f three': 'Rf3',
  'rook f three': 'Rf3',
  'rook takes f three': 'Rxf3',
  'rook captures f three': 'Rxf3',
  'r f four': 'Rf4',
  'rook to f four': 'Rf4',
  'rook f four': 'Rf4',
  'rook takes f four': 'Rxf4',
  'rook captures f four': 'Rxf4',
  'r f five': 'Rf5',
  'rook to f five': 'Rf5',
  'rook f five': 'Rf5',
  'rook takes f five': 'Rxf5',
  'rook captures f five': 'Rxf5',
  'r f six': 'Rf6',
  'rook to f six': 'Rf6',
  'rook f six': 'Rf6',
  'rook takes f six': 'Rxf6',
  'rook captures f six': 'Rxf6',
  'r f seven': 'Rf7',
  'rook to f seven': 'Rf7',
  'rook f seven': 'Rf7',
  'rook takes f seven': 'Rxf7',
  'rook captures f seven': 'Rxf7',
  'r f eight': 'Rf8',
  'rook to f eight': 'Rf8',
  'rook f eight': 'Rf8',
  'rook takes f eight': 'Rxf8',
  'rook captures f eight': 'Rxf8',
  'r g one': 'Rg1',
  'rook to g one': 'Rg1',
  'rook g one': 'Rg1',
  'rook takes g one': 'Rxg1',
  'rook captures g one': 'Rxg1',
  'r g two': 'Rg2',
  'rook to g two': 'Rg2',
  'rook g two': 'Rg2',
  'rook takes g two': 'Rxg2',
  'rook captures g two': 'Rxg2',
  'r g three': 'Rg3',
  'rook to g three': 'Rg3',
  'rook g three': 'Rg3',
  'rook takes g three': 'Rxg3',
  'rook captures g three': 'Rxg3',
  'r g four': 'Rg4',
  'rook to g four': 'Rg4',
  'rook g four': 'Rg4',
  'rook takes g four': 'Rxg4',
  'rook captures g four': 'Rxg4',
  'r g five': 'Rg5',
  'rook to g five': 'Rg5',
  'rook g five': 'Rg5',
  'rook takes g five': 'Rxg5',
  'rook captures g five': 'Rxg5',
  'r g six': 'Rg6',
  'rook to g six': 'Rg6',
  'rook g six': 'Rg6',
  'rook takes g six': 'Rxg6',
  'rook captures g six': 'Rxg6',
  'r g seven': 'Rg7',
  'rook to g seven': 'Rg7',
  'rook g seven': 'Rg7',
  'rook takes g seven': 'Rxg7',
  'rook captures g seven': 'Rxg7',
  'r g eight': 'Rg8',
  'rook to g eight': 'Rg8',
  'rook g eight': 'Rg8',
  'rook takes g eight': 'Rxg8',
  'rook captures g eight': 'Rxg8',
  'r h one': 'Rh1',
  'rook to h one': 'Rh1',
  'rook h one': 'Rh1',
  'rook takes h one': 'Rxh1',
  'rook captures h one': 'Rxh1',
  'r h two': 'Rh2',
  'rook to h two': 'Rh2',
  'rook h two': 'Rh2',
  'rook takes h two': 'Rxh2',
  'rook captures h two': 'Rxh2',
  'r h three': 'Rh3',
  'rook to h three': 'Rh3',
  'rook h three': 'Rh3',
  'rook takes h three': 'Rxh3',
  'rook captures h three': 'Rxh3',
  'r h four': 'Rh4',
  'rook to h four': 'Rh4',
  'rook h four': 'Rh4',
  'rook takes h four': 'Rxh4',
  'rook captures h four': 'Rxh4',
  'r h five': 'Rh5',
  'rook to h five': 'Rh5',
  'rook h five': 'Rh5',
  'rook takes h five': 'Rxh5',
  'rook captures h five': 'Rxh5',
  'r h six': 'Rh6',
  'rook to h six': 'Rh6',
  'rook h six': 'Rh6',
  'rook takes h six': 'Rxh6',
  'rook captures h six': 'Rxh6',
  'r h seven': 'Rh7',
  'rook to h seven': 'Rh7',
  'rook h seven': 'Rh7',
  'rook takes h seven': 'Rxh7',
  'rook captures h seven': 'Rxh7',
  'r h eight': 'Rh8',
  'rook to h eight': 'Rh8',
  'rook h eight': 'Rh8',
  'rook takes h eight': 'Rxh8',
  'rook captures h eight': 'Rxh8',

  // Queen moves
  'q a one': 'Qa1',
  'queen to a one': 'Qa1',
  'queen a one': 'Qa1',
  'queen takes a one': 'Qxa1',
  'queen captures a one': 'Qxa1',
  'q a two': 'Qa2',
  'queen to a two': 'Qa2',
  'queen a two': 'Qa2',
  'queen takes a two': 'Qxa2',
  'queen captures a two': 'Qxa2',
  'q a three': 'Qa3',
  'queen to a three': 'Qa3',
  'queen a three': 'Qa3',
  'queen takes a three': 'Qxa3',
  'queen captures a three': 'Qxa3',
  'q a four': 'Qa4',
  'queen to a four': 'Qa4',
  'queen a four': 'Qa4',
  'queen takes a four': 'Qxa4',
  'queen captures a four': 'Qxa4',
  'q a five': 'Qa5',
  'queen to a five': 'Qa5',
  'queen a five': 'Qa5',
  'queen takes a five': 'Qxa5',
  'queen captures a five': 'Qxa5',
  'q a six': 'Qa6',
  'queen to a six': 'Qa6',
  'queen a six': 'Qa6',
  'queen takes a six': 'Qxa6',
  'queen captures a six': 'Qxa6',
  'q a seven': 'Qa7',
  'queen to a seven': 'Qa7',
  'queen a seven': 'Qa7',
  'queen takes a seven': 'Qxa7',
  'queen captures a seven': 'Qxa7',
  'q a eight': 'Qa8',
  'queen to a eight': 'Qa8',
  'queen a eight': 'Qa8',
  'queen takes a eight': 'Qxa8',
  'queen captures a eight': 'Qxa8',
  'q b one': 'Qb1',
  'queen to b one': 'Qb1',
  'queen b one': 'Qb1',
  'queen takes b one': 'Qxb1',
  'queen captures b one': 'Qxb1',
  'q b two': 'Qb2',
  'queen to b two': 'Qb2',
  'queen b two': 'Qb2',
  'queen takes b two': 'Qxb2',
  'queen captures b two': 'Qxb2',
  'q b three': 'Qb3',
  'queen to b three': 'Qb3',
  'queen b three': 'Qb3',
  'queen takes b three': 'Qxb3',
  'queen captures b three': 'Qxb3',
  'q b four': 'Qb4',
  'queen to b four': 'Qb4',
  'queen b four': 'Qb4',
  'queen takes b four': 'Qxb4',
  'queen captures b four': 'Qxb4',
  'q b five': 'Qb5',
  'queen to b five': 'Qb5',
  'queen b five': 'Qb5',
  'queen takes b five': 'Qxb5',
  'queen captures b five': 'Qxb5',
  'q b six': 'Qb6',
  'queen to b six': 'Qb6',
  'queen b six': 'Qb6',
  'queen takes b six': 'Qxb6',
  'queen captures b six': 'Qxb6',
  'q b seven': 'Qb7',
  'queen to b seven': 'Qb7',
  'queen b seven': 'Qb7',
  'queen takes b seven': 'Qxb7',
  'queen captures b seven': 'Qxb7',
  'q b eight': 'Qb8',
  'queen to b eight': 'Qb8',
  'queen b eight': 'Qb8',
  'queen takes b eight': 'Qxb8',
  'queen captures b eight': 'Qxb8',
  'q c one': 'Qc1',
  'queen to c one': 'Qc1',
  'queen c one': 'Qc1',
  'queen takes c one': 'Qxc1',
  'queen captures c one': 'Qxc1',
  'q c two': 'Qc2',
  'queen to c two': 'Qc2',
  'queen c two': 'Qc2',
  'queen takes c two': 'Qxc2',
  'queen captures c two': 'Qxc2',
  'q c three': 'Qc3',
  'queen to c three': 'Qc3',
  'queen c three': 'Qc3',
  'queen takes c three': 'Qxc3',
  'queen captures c three': 'Qxc3',
  'q c four': 'Qc4',
  'queen to c four': 'Qc4',
  'queen c four': 'Qc4',
  'queen takes c four': 'Qxc4',
  'queen captures c four': 'Qxc4',
  'q c five': 'Qc5',
  'queen to c five': 'Qc5',
  'queen c five': 'Qc5',
  'queen takes c five': 'Qxc5',
  'queen captures c five': 'Qxc5',
  'q c six': 'Qc6',
  'queen to c six': 'Qc6',
  'queen c six': 'Qc6',
  'queen takes c six': 'Qxc6',
  'queen captures c six': 'Qxc6',
  'q c seven': 'Qc7',
  'queen to c seven': 'Qc7',
  'queen c seven': 'Qc7',
  'queen takes c seven': 'Qxc7',
  'queen captures c seven': 'Qxc7',
  'q c eight': 'Qc8',
  'queen to c eight': 'Qc8',
  'queen c eight': 'Qc8',
  'queen takes c eight': 'Qxc8',
  'queen captures c eight': 'Qxc8',
  'q d one': 'Qd1',
  'queen to d one': 'Qd1',
  'queen d one': 'Qd1',
  'queen takes d one': 'Qxd1',
  'queen captures d one': 'Qxd1',
  'q d two': 'Qd2',
  'queen to d two': 'Qd2',
  'queen d two': 'Qd2',
  'queen takes d two': 'Qxd2',
  'queen captures d two': 'Qxd2',
  'q d three': 'Qd3',
  'queen to d three': 'Qd3',
  'queen d three': 'Qd3',
  'queen takes d three': 'Qxd3',
  'queen captures d three': 'Qxd3',
  'q d four': 'Qd4',
  'queen to d four': 'Qd4',
  'queen d four': 'Qd4',
  'queen takes d four': 'Qxd4',
  'queen captures d four': 'Qxd4',
  'q d five': 'Qd5',
  'queen to d five': 'Qd5',
  'queen d five': 'Qd5',
  'queen takes d five': 'Qxd5',
  'queen captures d five': 'Qxd5',
  'q d six': 'Qd6',
  'queen to d six': 'Qd6',
  'queen d six': 'Qd6',
  'queen takes d six': 'Qxd6',
  'queen captures d six': 'Qxd6',
  'q d seven': 'Qd7',
  'queen to d seven': 'Qd7',
  'queen d seven': 'Qd7',
  'queen takes d seven': 'Qxd7',
  'queen captures d seven': 'Qxd7',
  'q d eight': 'Qd8',
  'queen to d eight': 'Qd8',
  'queen d eight': 'Qd8',
  'queen takes d eight': 'Qxd8',
  'queen captures d eight': 'Qxd8',
  'q e one': 'Qe1',
  'queen to e one': 'Qe1',
  'queen e one': 'Qe1',
  'queen takes e one': 'Qxe1',
  'queen captures e one': 'Qxe1',
  'q e two': 'Qe2',
  'queen to e two': 'Qe2',
  'queen e two': 'Qe2',
  'queen takes e two': 'Qxe2',
  'queen captures e two': 'Qxe2',
  'q e three': 'Qe3',
  'queen to e three': 'Qe3',
  'queen e three': 'Qe3',
  'queen takes e three': 'Qxe3',
  'queen captures e three': 'Qxe3',
  'q e four': 'Qe4',
  'queen to e four': 'Qe4',
  'queen e four': 'Qe4',
  'queen takes e four': 'Qxe4',
  'queen captures e four': 'Qxe4',
  'q e five': 'Qe5',
  'queen to e five': 'Qe5',
  'queen e five': 'Qe5',
  'queen takes e five': 'Qxe5',
  'queen captures e five': 'Qxe5',
  'q e six': 'Qe6',
  'queen to e six': 'Qe6',
  'queen e six': 'Qe6',
  'queen takes e six': 'Qxe6',
  'queen captures e six': 'Qxe6',
  'q e seven': 'Qe7',
  'queen to e seven': 'Qe7',
  'queen e seven': 'Qe7',
  'queen takes e seven': 'Qxe7',
  'queen captures e seven': 'Qxe7',
  'q e eight': 'Qe8',
  'queen to e eight': 'Qe8',
  'queen e eight': 'Qe8',
  'queen takes e eight': 'Qxe8',
  'queen captures e eight': 'Qxe8',
  'q f one': 'Qf1',
  'queen to f one': 'Qf1',
  'queen f one': 'Qf1',
  'queen takes f one': 'Qxf1',
  'queen captures f one': 'Qxf1',
  'q f two': 'Qf2',
  'queen to f two': 'Qf2',
  'queen f two': 'Qf2',
  'queen takes f two': 'Qxf2',
  'queen captures f two': 'Qxf2',
  'q f three': 'Qf3',
  'queen to f three': 'Qf3',
  'queen f three': 'Qf3',
  'queen takes f three': 'Qxf3',
  'queen captures f three': 'Qxf3',
  'q f four': 'Qf4',
  'queen to f four': 'Qf4',
  'queen f four': 'Qf4',
  'queen takes f four': 'Qxf4',
  'queen captures f four': 'Qxf4',
  'q f five': 'Qf5',
  'queen to f five': 'Qf5',
  'queen f five': 'Qf5',
  'queen takes f five': 'Qxf5',
  'queen captures f five': 'Qxf5',
  'q f six': 'Qf6',
  'queen to f six': 'Qf6',
  'queen f six': 'Qf6',
  'queen takes f six': 'Qxf6',
  'queen captures f six': 'Qxf6',
  'q f seven': 'Qf7',
  'queen to f seven': 'Qf7',
  'queen f seven': 'Qf7',
  'queen takes f seven': 'Qxf7',
  'queen captures f seven': 'Qxf7',
  'q f eight': 'Qf8',
  'queen to f eight': 'Qf8',
  'queen f eight': 'Qf8',
  'queen takes f eight': 'Qxf8',
  'queen captures f eight': 'Qxf8',
  'q g one': 'Qg1',
  'queen to g one': 'Qg1',
  'queen g one': 'Qg1',
  'queen takes g one': 'Qxg1',
  'queen captures g one': 'Qxg1',
  'q g two': 'Qg2',
  'queen to g two': 'Qg2',
  'queen g two': 'Qg2',
  'queen takes g two': 'Qxg2',
  'queen captures g two': 'Qxg2',
  'q g three': 'Qg3',
  'queen to g three': 'Qg3',
  'queen g three': 'Qg3',
  'queen takes g three': 'Qxg3',
  'queen captures g three': 'Qxg3',
  'q g four': 'Qg4',
  'queen to g four': 'Qg4',
  'queen g four': 'Qg4',
  'queen takes g four': 'Qxg4',
  'queen captures g four': 'Qxg4',
  'q g five': 'Qg5',
  'queen to g five': 'Qg5',
  'queen g five': 'Qg5',
  'queen takes g five': 'Qxg5',
  'queen captures g five': 'Qxg5',
  'q g six': 'Qg6',
  'queen to g six': 'Qg6',
  'queen g six': 'Qg6',
  'queen takes g six': 'Qxg6',
  'queen captures g six': 'Qxg6',
  'q g seven': 'Qg7',
  'queen to g seven': 'Qg7',
  'queen g seven': 'Qg7',
  'queen takes g seven': 'Qxg7',
  'queen captures g seven': 'Qxg7',
  'q g eight': 'Qg8',
  'queen to g eight': 'Qg8',
  'queen g eight': 'Qg8',
  'queen takes g eight': 'Qxg8',
  'queen captures g eight': 'Qxg8',
  'q h one': 'Qh1',
  'queen to h one': 'Qh1',
  'queen h one': 'Qh1',
  'queen takes h one': 'Qxh1',
  'queen captures h one': 'Qxh1',
  'q h two': 'Qh2',
  'queen to h two': 'Qh2',
  'queen h two': 'Qh2',
  'queen takes h two': 'Qxh2',
  'queen captures h two': 'Qxh2',
  'q h three': 'Qh3',
  'queen to h three': 'Qh3',
  'queen h three': 'Qh3',
  'queen takes h three': 'Qxh3',
  'queen captures h three': 'Qxh3',
  'q h four': 'Qh4',
  'queen to h four': 'Qh4',
  'queen h four': 'Qh4',
  'queen takes h four': 'Qxh4',
  'queen captures h four': 'Qxh4',
  'q h five': 'Qh5',
  'queen to h five': 'Qh5',
  'queen h five': 'Qh5',
  'queen takes h five': 'Qxh5',
  'queen captures h five': 'Qxh5',
  'q h six': 'Qh6',
  'queen to h six': 'Qh6',
  'queen h six': 'Qh6',
  'queen takes h six': 'Qxh6',
  'queen captures h six': 'Qxh6',
  'q h seven': 'Qh7',
  'queen to h seven': 'Qh7',
  'queen h seven': 'Qh7',
  'queen takes h seven': 'Qxh7',
  'queen captures h seven': 'Qxh7',
  'q h eight': 'Qh8',
  'queen to h eight': 'Qh8',
  'queen h eight': 'Qh8',
  'queen takes h eight': 'Qxh8',
  'queen captures h eight': 'Qxh8',

  // King moves
  'k a one': 'Ka1',
  'king to a one': 'Ka1',
  'king a one': 'Ka1',
  'king takes a one': 'Kxa1',
  'king captures a one': 'Kxa1',
  'k a two': 'Ka2',
  'king to a two': 'Ka2',
  'king a two': 'Ka2',
  'king takes a two': 'Kxa2',
  'king captures a two': 'Kxa2',
  'k a three': 'Ka3',
  'king to a three': 'Ka3',
  'king a three': 'Ka3',
  'king takes a three': 'Kxa3',
  'king captures a three': 'Kxa3',
  'k a four': 'Ka4',
  'king to a four': 'Ka4',
  'king a four': 'Ka4',
  'king takes a four': 'Kxa4',
  'king captures a four': 'Kxa4',
  'k a five': 'Ka5',
  'king to a five': 'Ka5',
  'king a five': 'Ka5',
  'king takes a five': 'Kxa5',
  'king captures a five': 'Kxa5',
  'k a six': 'Ka6',
  'king to a six': 'Ka6',
  'king a six': 'Ka6',
  'king takes a six': 'Kxa6',
  'king captures a six': 'Kxa6',
  'k a seven': 'Ka7',
  'king to a seven': 'Ka7',
  'king a seven': 'Ka7',
  'king takes a seven': 'Kxa7',
  'king captures a seven': 'Kxa7',
  'k a eight': 'Ka8',
  'king to a eight': 'Ka8',
  'king a eight': 'Ka8',
  'king takes a eight': 'Kxa8',
  'king captures a eight': 'Kxa8',
  'k b one': 'Kb1',
  'king to b one': 'Kb1',
  'king b one': 'Kb1',
  'king takes b one': 'Kxb1',
  'king captures b one': 'Kxb1',
  'k b two': 'Kb2',
  'king to b two': 'Kb2',
  'king b two': 'Kb2',
  'king takes b two': 'Kxb2',
  'king captures b two': 'Kxb2',
  'k b three': 'Kb3',
  'king to b three': 'Kb3',
  'king b three': 'Kb3',
  'king takes b three': 'Kxb3',
  'king captures b three': 'Kxb3',
  'k b four': 'Kb4',
  'king to b four': 'Kb4',
  'king b four': 'Kb4',
  'king takes b four': 'Kxb4',
  'king captures b four': 'Kxb4',
  'k b five': 'Kb5',
  'king to b five': 'Kb5',
  'king b five': 'Kb5',
  'king takes b five': 'Kxb5',
  'king captures b five': 'Kxb5',
  'k b six': 'Kb6',
  'king to b six': 'Kb6',
  'king b six': 'Kb6',
  'king takes b six': 'Kxb6',
  'king captures b six': 'Kxb6',
  'k b seven': 'Kb7',
  'king to b seven': 'Kb7',
  'king b seven': 'Kb7',
  'king takes b seven': 'Kxb7',
  'king captures b seven': 'Kxb7',
  'k b eight': 'Kb8',
  'king to b eight': 'Kb8',
  'king b eight': 'Kb8',
  'king takes b eight': 'Kxb8',
  'king captures b eight': 'Kxb8',
  'k c one': 'Kc1',
  'king to c one': 'Kc1',
  'king c one': 'Kc1',
  'king takes c one': 'Kxc1',
  'king captures c one': 'Kxc1',
  'k c two': 'Kc2',
  'king to c two': 'Kc2',
  'king c two': 'Kc2',
  'king takes c two': 'Kxc2',
  'king captures c two': 'Kxc2',
  'k c three': 'Kc3',
  'king to c three': 'Kc3',
  'king c three': 'Kc3',
  'king takes c three': 'Kxc3',
  'king captures c three': 'Kxc3',
  'k c four': 'Kc4',
  'king to c four': 'Kc4',
  'king c four': 'Kc4',
  'king takes c four': 'Kxc4',
  'king captures c four': 'Kxc4',
  'k c five': 'Kc5',
  'king to c five': 'Kc5',
  'king c five': 'Kc5',
  'king takes c five': 'Kxc5',
  'king captures c five': 'Kxc5',
  'k c six': 'Kc6',
  'king to c six': 'Kc6',
  'king c six': 'Kc6',
  'king takes c six': 'Kxc6',
  'king captures c six': 'Kxc6',
  'k c seven': 'Kc7',
  'king to c seven': 'Kc7',
  'king c seven': 'Kc7',
  'king takes c seven': 'Kxc7',
  'king captures c seven': 'Kxc7',
  'k c eight': 'Kc8',
  'king to c eight': 'Kc8',
  'king c eight': 'Kc8',
  'king takes c eight': 'Kxc8',
  'king captures c eight': 'Kxc8',
  'k d one': 'Kd1',
  'king to d one': 'Kd1',
  'king d one': 'Kd1',
  'king takes d one': 'Kxd1',
  'king captures d one': 'Kxd1',
  'k d two': 'Kd2',
  'king to d two': 'Kd2',
  'king d two': 'Kd2',
  'king takes d two': 'Kxd2',
  'king captures d two': 'Kxd2',
  'k d three': 'Kd3',
  'king to d three': 'Kd3',
  'king d three': 'Kd3',
  'king takes d three': 'Kxd3',
  'king captures d three': 'Kxd3',
  'k d four': 'Kd4',
  'king to d four': 'Kd4',
  'king d four': 'Kd4',
  'king takes d four': 'Kxd4',
  'king captures d four': 'Kxd4',
  'k d five': 'Kd5',
  'king to d five': 'Kd5',
  'king d five': 'Kd5',
  'king takes d five': 'Kxd5',
  'king captures d five': 'Kxd5',
  'k d six': 'Kd6',
  'king to d six': 'Kd6',
  'king d six': 'Kd6',
  'king takes d six': 'Kxd6',
  'king captures d six': 'Kxd6',
  'k d seven': 'Kd7',
  'king to d seven': 'Kd7',
  'king d seven': 'Kd7',
  'king takes d seven': 'Kxd7',
  'king captures d seven': 'Kxd7',
  'k d eight': 'Kd8',
  'king to d eight': 'Kd8',
  'king d eight': 'Kd8',
  'king takes d eight': 'Kxd8',
  'king captures d eight': 'Kxd8',
  'k e one': 'Ke1',
  'king to e one': 'Ke1',
  'king e one': 'Ke1',
  'king takes e one': 'Kxe1',
  'king captures e one': 'Kxe1',
  'k e two': 'Ke2',
  'king to e two': 'Ke2',
  'king e two': 'Ke2',
  'king takes e two': 'Kxe2',
  'king captures e two': 'Kxe2',
  'k e three': 'Ke3',
  'king to e three': 'Ke3',
  'king e three': 'Ke3',
  'king takes e three': 'Kxe3',
  'king captures e three': 'Kxe3',
  'k e four': 'Ke4',
  'king to e four': 'Ke4',
  'king e four': 'Ke4',
  'king takes e four': 'Kxe4',
  'king captures e four': 'Kxe4',
  'k e five': 'Ke5',
  'king to e five': 'Ke5',
  'king e five': 'Ke5',
  'king takes e five': 'Kxe5',
  'king captures e five': 'Kxe5',
  'k e six': 'Ke6',
  'king to e six': 'Ke6',
  'king e six': 'Ke6',
  'king takes e six': 'Kxe6',
  'king captures e six': 'Kxe6',
  'k e seven': 'Ke7',
  'king to e seven': 'Ke7',
  'king e seven': 'Ke7',
  'king takes e seven': 'Kxe7',
  'king captures e seven': 'Kxe7',
  'k e eight': 'Ke8',
  'king to e eight': 'Ke8',
  'king e eight': 'Ke8',
  'king takes e eight': 'Kxe8',
  'king captures e eight': 'Kxe8',
  'k f one': 'Kf1',
  'king to f one': 'Kf1',
  'king f one': 'Kf1',
  'king takes f one': 'Kxf1',
  'king captures f one': 'Kxf1',
  'k f two': 'Kf2',
  'king to f two': 'Kf2',
  'king f two': 'Kf2',
  'king takes f two': 'Kxf2',
  'king captures f two': 'Kxf2',
  'k f three': 'Kf3',
  'king to f three': 'Kf3',
  'king f three': 'Kf3',
  'king takes f three': 'Kxf3',
  'king captures f three': 'Kxf3',
  'k f four': 'Kf4',
  'king to f four': 'Kf4',
  'king f four': 'Kf4',
  'king takes f four': 'Kxf4',
  'king captures f four': 'Kxf4',
  'k f five': 'Kf5',
  'king to f five': 'Kf5',
  'king f five': 'Kf5',
  'king takes f five': 'Kxf5',
  'king captures f five': 'Kxf5',
  'k f six': 'Kf6',
  'king to f six': 'Kf6',
  'king f six': 'Kf6',
  'king takes f six': 'Kxf6',
  'king captures f six': 'Kxf6',
  'k f seven': 'Kf7',
  'king to f seven': 'Kf7',
  'king f seven': 'Kf7',
  'king takes f seven': 'Kxf7',
  'king captures f seven': 'Kxf7',
  'k f eight': 'Kf8',
  'king to f eight': 'Kf8',
  'king f eight': 'Kf8',
  'king takes f eight': 'Kxf8',
  'king captures f eight': 'Kxf8',
  'k g one': 'Kg1',
  'king to g one': 'Kg1',
  'king g one': 'Kg1',
  'king takes g one': 'Kxg1',
  'king captures g one': 'Kxg1',
  'k g two': 'Kg2',
  'king to g two': 'Kg2',
  'king g two': 'Kg2',
  'king takes g two': 'Kxg2',
  'king captures g two': 'Kxg2',
  'k g three': 'Kg3',
  'king to g three': 'Kg3',
  'king g three': 'Kg3',
  'king takes g three': 'Kxg3',
  'king captures g three': 'Kxg3',
  'k g four': 'Kg4',
  'king to g four': 'Kg4',
  'king g four': 'Kg4',
  'king takes g four': 'Kxg4',
  'king captures g four': 'Kxg4',
  'k g five': 'Kg5',
  'king to g five': 'Kg5',
  'king g five': 'Kg5',
  'king takes g five': 'Kxg5',
  'king captures g five': 'Kxg5',
  'k g six': 'Kg6',
  'king to g six': 'Kg6',
  'king g six': 'Kg6',
  'king takes g six': 'Kxg6',
  'king captures g six': 'Kxg6',
  'k g seven': 'Kg7',
  'king to g seven': 'Kg7',
  'king g seven': 'Kg7',
  'king takes g seven': 'Kxg7',
  'king captures g seven': 'Kxg7',
  'k g eight': 'Kg8',
  'king to g eight': 'Kg8',
  'king g eight': 'Kg8',
  'king takes g eight': 'Kxg8',
  'king captures g eight': 'Kxg8',
  'k h one': 'Kh1',
  'king to h one': 'Kh1',
  'king h one': 'Kh1',
  'king takes h one': 'Kxh1',
  'king captures h one': 'Kxh1',
  'k h two': 'Kh2',
  'king to h two': 'Kh2',
  'king h two': 'Kh2',
  'king takes h two': 'Kxh2',
  'king captures h two': 'Kxh2',
  'k h three': 'Kh3',
  'king to h three': 'Kh3',
  'king h three': 'Kh3',
  'king takes h three': 'Kxh3',
  'king captures h three': 'Kxh3',
  'k h four': 'Kh4',
  'king to h four': 'Kh4',
  'king h four': 'Kh4',
  'king takes h four': 'Kxh4',
  'king captures h four': 'Kxh4',
  'k h five': 'Kh5',
  'king to h five': 'Kh5',
  'king h five': 'Kh5',
  'king takes h five': 'Kxh5',
  'king captures h five': 'Kxh5',
  'k h six': 'Kh6',
  'king to h six': 'Kh6',
  'king h six': 'Kh6',
  'king takes h six': 'Kxh6',
  'king captures h six': 'Kxh6',
  'k h seven': 'Kh7',
  'king to h seven': 'Kh7',
  'king h seven': 'Kh7',
  'king takes h seven': 'Kxh7',
  'king captures h seven': 'Kxh7',
  'k h eight': 'Kh8',
  'king to h eight': 'Kh8',
  'king h eight': 'Kh8',
  'king takes h eight': 'Kxh8',
  'king captures h eight': 'Kxh8',

  // Pawn file captures: 'a takes <dst> <rank>'
  'a takes b one': 'axb1',
  'a takes c one': 'axc1',
  'a takes d one': 'axd1',
  'a takes e one': 'axe1',
  'a takes f one': 'axf1',
  'a takes g one': 'axg1',
  'a takes h one': 'axh1',
  'a takes b two': 'axb2',
  'a takes c two': 'axc2',
  'a takes d two': 'axd2',
  'a takes e two': 'axe2',
  'a takes f two': 'axf2',
  'a takes g two': 'axg2',
  'a takes h two': 'axh2',
  'a takes b three': 'axb3',
  'a takes c three': 'axc3',
  'a takes d three': 'axd3',
  'a takes e three': 'axe3',
  'a takes f three': 'axf3',
  'a takes g three': 'axg3',
  'a takes h three': 'axh3',
  'a takes b four': 'axb4',
  'a takes c four': 'axc4',
  'a takes d four': 'axd4',
  'a takes e four': 'axe4',
  'a takes f four': 'axf4',
  'a takes g four': 'axg4',
  'a takes h four': 'axh4',
  'a takes b five': 'axb5',
  'a takes c five': 'axc5',
  'a takes d five': 'axd5',
  'a takes e five': 'axe5',
  'a takes f five': 'axf5',
  'a takes g five': 'axg5',
  'a takes h five': 'axh5',
  'a takes b six': 'axb6',
  'a takes c six': 'axc6',
  'a takes d six': 'axd6',
  'a takes e six': 'axe6',
  'a takes f six': 'axf6',
  'a takes g six': 'axg6',
  'a takes h six': 'axh6',
  'a takes b seven': 'axb7',
  'a takes c seven': 'axc7',
  'a takes d seven': 'axd7',
  'a takes e seven': 'axe7',
  'a takes f seven': 'axf7',
  'a takes g seven': 'axg7',
  'a takes h seven': 'axh7',
  'a takes b eight': 'axb8',
  'a takes c eight': 'axc8',
  'a takes d eight': 'axd8',
  'a takes e eight': 'axe8',
  'a takes f eight': 'axf8',
  'a takes g eight': 'axg8',
  'a takes h eight': 'axh8',
  'b takes a one': 'bxa1',
  'b takes c one': 'bxc1',
  'b takes d one': 'bxd1',
  'b takes e one': 'bxe1',
  'b takes f one': 'bxf1',
  'b takes g one': 'bxg1',
  'b takes h one': 'bxh1',
  'b takes a two': 'bxa2',
  'b takes c two': 'bxc2',
  'b takes d two': 'bxd2',
  'b takes e two': 'bxe2',
  'b takes f two': 'bxf2',
  'b takes g two': 'bxg2',
  'b takes h two': 'bxh2',
  'b takes a three': 'bxa3',
  'b takes c three': 'bxc3',
  'b takes d three': 'bxd3',
  'b takes e three': 'bxe3',
  'b takes f three': 'bxf3',
  'b takes g three': 'bxg3',
  'b takes h three': 'bxh3',
  'b takes a four': 'bxa4',
  'b takes c four': 'bxc4',
  'b takes d four': 'bxd4',
  'b takes e four': 'bxe4',
  'b takes f four': 'bxf4',
  'b takes g four': 'bxg4',
  'b takes h four': 'bxh4',
  'b takes a five': 'bxa5',
  'b takes c five': 'bxc5',
  'b takes d five': 'bxd5',
  'b takes e five': 'bxe5',
  'b takes f five': 'bxf5',
  'b takes g five': 'bxg5',
  'b takes h five': 'bxh5',
  'b takes a six': 'bxa6',
  'b takes c six': 'bxc6',
  'b takes d six': 'bxd6',
  'b takes e six': 'bxe6',
  'b takes f six': 'bxf6',
  'b takes g six': 'bxg6',
  'b takes h six': 'bxh6',
  'b takes a seven': 'bxa7',
  'b takes c seven': 'bxc7',
  'b takes d seven': 'bxd7',
  'b takes e seven': 'bxe7',
  'b takes f seven': 'bxf7',
  'b takes g seven': 'bxg7',
  'b takes h seven': 'bxh7',
  'b takes a eight': 'bxa8',
  'b takes c eight': 'bxc8',
  'b takes d eight': 'bxd8',
  'b takes e eight': 'bxe8',
  'b takes f eight': 'bxf8',
  'b takes g eight': 'bxg8',
  'b takes h eight': 'bxh8',
  'c takes a one': 'cxa1',
  'c takes b one': 'cxb1',
  'c takes d one': 'cxd1',
  'c takes e one': 'cxe1',
  'c takes f one': 'cxf1',
  'c takes g one': 'cxg1',
  'c takes h one': 'cxh1',
  'c takes a two': 'cxa2',
  'c takes b two': 'cxb2',
  'c takes d two': 'cxd2',
  'c takes e two': 'cxe2',
  'c takes f two': 'cxf2',
  'c takes g two': 'cxg2',
  'c takes h two': 'cxh2',
  'c takes a three': 'cxa3',
  'c takes b three': 'cxb3',
  'c takes d three': 'cxd3',
  'c takes e three': 'cxe3',
  'c takes f three': 'cxf3',
  'c takes g three': 'cxg3',
  'c takes h three': 'cxh3',
  'c takes a four': 'cxa4',
  'c takes b four': 'cxb4',
  'c takes d four': 'cxd4',
  'c takes e four': 'cxe4',
  'c takes f four': 'cxf4',
  'c takes g four': 'cxg4',
  'c takes h four': 'cxh4',
  'c takes a five': 'cxa5',
  'c takes b five': 'cxb5',
  'c takes d five': 'cxd5',
  'c takes e five': 'cxe5',
  'c takes f five': 'cxf5',
  'c takes g five': 'cxg5',
  'c takes h five': 'cxh5',
  'c takes a six': 'cxa6',
  'c takes b six': 'cxb6',
  'c takes d six': 'cxd6',
  'c takes e six': 'cxe6',
  'c takes f six': 'cxf6',
  'c takes g six': 'cxg6',
  'c takes h six': 'cxh6',
  'c takes a seven': 'cxa7',
  'c takes b seven': 'cxb7',
  'c takes d seven': 'cxd7',
  'c takes e seven': 'cxe7',
  'c takes f seven': 'cxf7',
  'c takes g seven': 'cxg7',
  'c takes h seven': 'cxh7',
  'c takes a eight': 'cxa8',
  'c takes b eight': 'cxb8',
  'c takes d eight': 'cxd8',
  'c takes e eight': 'cxe8',
  'c takes f eight': 'cxf8',
  'c takes g eight': 'cxg8',
  'c takes h eight': 'cxh8',
  'd takes a one': 'dxa1',
  'd takes b one': 'dxb1',
  'd takes c one': 'dxc1',
  'd takes e one': 'dxe1',
  'd takes f one': 'dxf1',
  'd takes g one': 'dxg1',
  'd takes h one': 'dxh1',
  'd takes a two': 'dxa2',
  'd takes b two': 'dxb2',
  'd takes c two': 'dxc2',
  'd takes e two': 'dxe2',
  'd takes f two': 'dxf2',
  'd takes g two': 'dxg2',
  'd takes h two': 'dxh2',
  'd takes a three': 'dxa3',
  'd takes b three': 'dxb3',
  'd takes c three': 'dxc3',
  'd takes e three': 'dxe3',
  'd takes f three': 'dxf3',
  'd takes g three': 'dxg3',
  'd takes h three': 'dxh3',
  'd takes a four': 'dxa4',
  'd takes b four': 'dxb4',
  'd takes c four': 'dxc4',
  'd takes e four': 'dxe4',
  'd takes f four': 'dxf4',
  'd takes g four': 'dxg4',
  'd takes h four': 'dxh4',
  'd takes a five': 'dxa5',
  'd takes b five': 'dxb5',
  'd takes c five': 'dxc5',
  'd takes e five': 'dxe5',
  'd takes f five': 'dxf5',
  'd takes g five': 'dxg5',
  'd takes h five': 'dxh5',
  'd takes a six': 'dxa6',
  'd takes b six': 'dxb6',
  'd takes c six': 'dxc6',
  'd takes e six': 'dxe6',
  'd takes f six': 'dxf6',
  'd takes g six': 'dxg6',
  'd takes h six': 'dxh6',
  'd takes a seven': 'dxa7',
  'd takes b seven': 'dxb7',
  'd takes c seven': 'dxc7',
  'd takes e seven': 'dxe7',
  'd takes f seven': 'dxf7',
  'd takes g seven': 'dxg7',
  'd takes h seven': 'dxh7',
  'd takes a eight': 'dxa8',
  'd takes b eight': 'dxb8',
  'd takes c eight': 'dxc8',
  'd takes e eight': 'dxe8',
  'd takes f eight': 'dxf8',
  'd takes g eight': 'dxg8',
  'd takes h eight': 'dxh8',
  'e takes a one': 'exa1',
  'e takes b one': 'exb1',
  'e takes c one': 'exc1',
  'e takes d one': 'exd1',
  'e takes f one': 'exf1',
  'e takes g one': 'exg1',
  'e takes h one': 'exh1',
  'e takes a two': 'exa2',
  'e takes b two': 'exb2',
  'e takes c two': 'exc2',
  'e takes d two': 'exd2',
  'e takes f two': 'exf2',
  'e takes g two': 'exg2',
  'e takes h two': 'exh2',
  'e takes a three': 'exa3',
  'e takes b three': 'exb3',
  'e takes c three': 'exc3',
  'e takes d three': 'exd3',
  'e takes f three': 'exf3',
  'e takes g three': 'exg3',
  'e takes h three': 'exh3',
  'e takes a four': 'exa4',
  'e takes b four': 'exb4',
  'e takes c four': 'exc4',
  'e takes d four': 'exd4',
  'e takes f four': 'exf4',
  'e takes g four': 'exg4',
  'e takes h four': 'exh4',
  'e takes a five': 'exa5',
  'e takes b five': 'exb5',
  'e takes c five': 'exc5',
  'e takes d five': 'exd5',
  'e takes f five': 'exf5',
  'e takes g five': 'exg5',
  'e takes h five': 'exh5',
  'e takes a six': 'exa6',
  'e takes b six': 'exb6',
  'e takes c six': 'exc6',
  'e takes d six': 'exd6',
  'e takes f six': 'exf6',
  'e takes g six': 'exg6',
  'e takes h six': 'exh6',
  'e takes a seven': 'exa7',
  'e takes b seven': 'exb7',
  'e takes c seven': 'exc7',
  'e takes d seven': 'exd7',
  'e takes f seven': 'exf7',
  'e takes g seven': 'exg7',
  'e takes h seven': 'exh7',
  'e takes a eight': 'exa8',
  'e takes b eight': 'exb8',
  'e takes c eight': 'exc8',
  'e takes d eight': 'exd8',
  'e takes f eight': 'exf8',
  'e takes g eight': 'exg8',
  'e takes h eight': 'exh8',
  'f takes a one': 'fxa1',
  'f takes b one': 'fxb1',
  'f takes c one': 'fxc1',
  'f takes d one': 'fxd1',
  'f takes e one': 'fxe1',
  'f takes g one': 'fxg1',
  'f takes h one': 'fxh1',
  'f takes a two': 'fxa2',
  'f takes b two': 'fxb2',
  'f takes c two': 'fxc2',
  'f takes d two': 'fxd2',
  'f takes e two': 'fxe2',
  'f takes g two': 'fxg2',
  'f takes h two': 'fxh2',
  'f takes a three': 'fxa3',
  'f takes b three': 'fxb3',
  'f takes c three': 'fxc3',
  'f takes d three': 'fxd3',
  'f takes e three': 'fxe3',
  'f takes g three': 'fxg3',
  'f takes h three': 'fxh3',
  'f takes a four': 'fxa4',
  'f takes b four': 'fxb4',
  'f takes c four': 'fxc4',
  'f takes d four': 'fxd4',
  'f takes e four': 'fxe4',
  'f takes g four': 'fxg4',
  'f takes h four': 'fxh4',
  'f takes a five': 'fxa5',
  'f takes b five': 'fxb5',
  'f takes c five': 'fxc5',
  'f takes d five': 'fxd5',
  'f takes e five': 'fxe5',
  'f takes g five': 'fxg5',
  'f takes h five': 'fxh5',
  'f takes a six': 'fxa6',
  'f takes b six': 'fxb6',
  'f takes c six': 'fxc6',
  'f takes d six': 'fxd6',
  'f takes e six': 'fxe6',
  'f takes g six': 'fxg6',
  'f takes h six': 'fxh6',
  'f takes a seven': 'fxa7',
  'f takes b seven': 'fxb7',
  'f takes c seven': 'fxc7',
  'f takes d seven': 'fxd7',
  'f takes e seven': 'fxe7',
  'f takes g seven': 'fxg7',
  'f takes h seven': 'fxh7',
  'f takes a eight': 'fxa8',
  'f takes b eight': 'fxb8',
  'f takes c eight': 'fxc8',
  'f takes d eight': 'fxd8',
  'f takes e eight': 'fxe8',
  'f takes g eight': 'fxg8',
  'f takes h eight': 'fxh8',
  'g takes a one': 'gxa1',
  'g takes b one': 'gxb1',
  'g takes c one': 'gxc1',
  'g takes d one': 'gxd1',
  'g takes e one': 'gxe1',
  'g takes f one': 'gxf1',
  'g takes h one': 'gxh1',
  'g takes a two': 'gxa2',
  'g takes b two': 'gxb2',
  'g takes c two': 'gxc2',
  'g takes d two': 'gxd2',
  'g takes e two': 'gxe2',
  'g takes f two': 'gxf2',
  'g takes h two': 'gxh2',
  'g takes a three': 'gxa3',
  'g takes b three': 'gxb3',
  'g takes c three': 'gxc3',
  'g takes d three': 'gxd3',
  'g takes e three': 'gxe3',
  'g takes f three': 'gxf3',
  'g takes h three': 'gxh3',
  'g takes a four': 'gxa4',
  'g takes b four': 'gxb4',
  'g takes c four': 'gxc4',
  'g takes d four': 'gxd4',
  'g takes e four': 'gxe4',
  'g takes f four': 'gxf4',
  'g takes h four': 'gxh4',
  'g takes a five': 'gxa5',
  'g takes b five': 'gxb5',
  'g takes c five': 'gxc5',
  'g takes d five': 'gxd5',
  'g takes e five': 'gxe5',
  'g takes f five': 'gxf5',
  'g takes h five': 'gxh5',
  'g takes a six': 'gxa6',
  'g takes b six': 'gxb6',
  'g takes c six': 'gxc6',
  'g takes d six': 'gxd6',
  'g takes e six': 'gxe6',
  'g takes f six': 'gxf6',
  'g takes h six': 'gxh6',
  'g takes a seven': 'gxa7',
  'g takes b seven': 'gxb7',
  'g takes c seven': 'gxc7',
  'g takes d seven': 'gxd7',
  'g takes e seven': 'gxe7',
  'g takes f seven': 'gxf7',
  'g takes h seven': 'gxh7',
  'g takes a eight': 'gxa8',
  'g takes b eight': 'gxb8',
  'g takes c eight': 'gxc8',
  'g takes d eight': 'gxd8',
  'g takes e eight': 'gxe8',
  'g takes f eight': 'gxf8',
  'g takes h eight': 'gxh8',
  'h takes a one': 'hxa1',
  'h takes b one': 'hxb1',
  'h takes c one': 'hxc1',
  'h takes d one': 'hxd1',
  'h takes e one': 'hxe1',
  'h takes f one': 'hxf1',
  'h takes g one': 'hxg1',
  'h takes a two': 'hxa2',
  'h takes b two': 'hxb2',
  'h takes c two': 'hxc2',
  'h takes d two': 'hxd2',
  'h takes e two': 'hxe2',
  'h takes f two': 'hxf2',
  'h takes g two': 'hxg2',
  'h takes a three': 'hxa3',
  'h takes b three': 'hxb3',
  'h takes c three': 'hxc3',
  'h takes d three': 'hxd3',
  'h takes e three': 'hxe3',
  'h takes f three': 'hxf3',
  'h takes g three': 'hxg3',
  'h takes a four': 'hxa4',
  'h takes b four': 'hxb4',
  'h takes c four': 'hxc4',
  'h takes d four': 'hxd4',
  'h takes e four': 'hxe4',
  'h takes f four': 'hxf4',
  'h takes g four': 'hxg4',
  'h takes a five': 'hxa5',
  'h takes b five': 'hxb5',
  'h takes c five': 'hxc5',
  'h takes d five': 'hxd5',
  'h takes e five': 'hxe5',
  'h takes f five': 'hxf5',
  'h takes g five': 'hxg5',
  'h takes a six': 'hxa6',
  'h takes b six': 'hxb6',
  'h takes c six': 'hxc6',
  'h takes d six': 'hxd6',
  'h takes e six': 'hxe6',
  'h takes f six': 'hxf6',
  'h takes g six': 'hxg6',
  'h takes a seven': 'hxa7',
  'h takes b seven': 'hxb7',
  'h takes c seven': 'hxc7',
  'h takes d seven': 'hxd7',
  'h takes e seven': 'hxe7',
  'h takes f seven': 'hxf7',
  'h takes g seven': 'hxg7',
  'h takes a eight': 'hxa8',
  'h takes b eight': 'hxb8',
  'h takes c eight': 'hxc8',
  'h takes d eight': 'hxd8',
  'h takes e eight': 'hxe8',
  'h takes f eight': 'hxf8',
  'h takes g eight': 'hxg8',

  /*[XXX: remove these?]
  // Pawn captures with 'pawn takes' (incomplete SAN — source file unknown)
  'pawn takes a one': null, 'pawn takes a two': null, 'pawn takes a three': null, 'pawn takes a four': null, 'pawn takes a five': null, 'pawn takes a six': null, 'pawn takes a seven': null, 'pawn takes a eight': null,
  'pawn takes b one': null, 'pawn takes b two': null, 'pawn takes b three': null, 'pawn takes b four': null, 'pawn takes b five': null, 'pawn takes b six': null, 'pawn takes b seven': null, 'pawn takes b eight': null,
  'pawn takes c one': null, 'pawn takes c two': null, 'pawn takes c three': null, 'pawn takes c four': null, 'pawn takes c five': null, 'pawn takes c six': null, 'pawn takes c seven': null, 'pawn takes c eight': null,
  'pawn takes d one': null, 'pawn takes d two': null, 'pawn takes d three': null, 'pawn takes d four': null, 'pawn takes d five': null, 'pawn takes d six': null, 'pawn takes d seven': null, 'pawn takes d eight': null,
  'pawn takes e one': null, 'pawn takes e two': null, 'pawn takes e three': null, 'pawn takes e four': null, 'pawn takes e five': null, 'pawn takes e six': null, 'pawn takes e seven': null, 'pawn takes e eight': null,
  'pawn takes f one': null, 'pawn takes f two': null, 'pawn takes f three': null, 'pawn takes f four': null, 'pawn takes f five': null, 'pawn takes f six': null, 'pawn takes f seven': null, 'pawn takes f eight': null,
  'pawn takes g one': null, 'pawn takes g two': null, 'pawn takes g three': null, 'pawn takes g four': null, 'pawn takes g five': null, 'pawn takes g six': null, 'pawn takes g seven': null, 'pawn takes g eight': null,
  'pawn takes h one': null, 'pawn takes h two': null, 'pawn takes h three': null, 'pawn takes h four': null, 'pawn takes h five': null, 'pawn takes h six': null, 'pawn takes h seven': null, 'pawn takes h eight': null,
   */

  // Castling
  'castle king side': 'O-O',
  // 'castle kingside': 'O-O',
  'castle queen side': 'O-O-O',
  // 'castle queenside': 'O-O-O',
  'king side castle': 'O-O',
  // 'kingside castle': 'O-O',
  'long castle': 'O-O-O',
  'castle long': 'O-O-O',
  'queen side castle': 'O-O-O',
  // 'queenside castle': 'O-O-O',
  'short castle': 'O-O',
  'castle short': 'O-O',

  // En passant captures
  'a takes b three en passant': 'axb3',
  'b takes a three en passant': 'bxa3',
  'b takes c three en passant': 'bxc3',
  'c takes b three en passant': 'cxb3',
  'c takes d three en passant': 'cxd3',
  'd takes c three en passant': 'dxc3',
  'd takes e three en passant': 'dxe3',
  'e takes d three en passant': 'exd3',
  'e takes f three en passant': 'exf3',
  'f takes e three en passant': 'fxe3',
  'f takes g three en passant': 'fxg3',
  'g takes f three en passant': 'gxf3',
  'g takes h three en passant': 'gxh3',
  'h takes g three en passant': 'hxg3',
  'a takes b six en passant': 'axb6',
  'b takes a six en passant': 'bxa6',
  'b takes c six en passant': 'bxc6',
  'c takes b six en passant': 'cxb6',
  'c takes d six en passant': 'cxd6',
  'd takes c six en passant': 'dxc6',
  'd takes e six en passant': 'dxe6',
  'e takes d six en passant': 'exd6',
  'e takes f six en passant': 'exf6',
  'f takes e six en passant': 'fxe6',
  'f takes g six en passant': 'fxg6',
  'g takes f six en passant': 'gxf6',
  'g takes h six en passant': 'gxh6',
  'h takes g six en passant': 'hxg6',

  // Pawn push promotions: '<square> <promotion phrase>'
  'a one bishop promotion': 'a1=B',
  'a eight bishop promotion': 'a8=B',
  'b one bishop promotion': 'b1=B',
  'b eight bishop promotion': 'b8=B',
  'c one bishop promotion': 'c1=B',
  'c eight bishop promotion': 'c8=B',
  'd one bishop promotion': 'd1=B',
  'd eight bishop promotion': 'd8=B',
  'e one bishop promotion': 'e1=B',
  'e eight bishop promotion': 'e8=B',
  'f one bishop promotion': 'f1=B',
  'f eight bishop promotion': 'f8=B',
  'g one bishop promotion': 'g1=B',
  'g eight bishop promotion': 'g8=B',
  'h one bishop promotion': 'h1=B',
  'h eight bishop promotion': 'h8=B',
  'a one knight promotion': 'a1=N',
  'a eight knight promotion': 'a8=N',
  'b one knight promotion': 'b1=N',
  'b eight knight promotion': 'b8=N',
  'c one knight promotion': 'c1=N',
  'c eight knight promotion': 'c8=N',
  'd one knight promotion': 'd1=N',
  'd eight knight promotion': 'd8=N',
  'e one knight promotion': 'e1=N',
  'e eight knight promotion': 'e8=N',
  'f one knight promotion': 'f1=N',
  'f eight knight promotion': 'f8=N',
  'g one knight promotion': 'g1=N',
  'g eight knight promotion': 'g8=N',
  'h one knight promotion': 'h1=N',
  'h eight knight promotion': 'h8=N',
  'a one queen promotion': 'a1=Q',
  'a eight queen promotion': 'a8=Q',
  'b one queen promotion': 'b1=Q',
  'b eight queen promotion': 'b8=Q',
  'c one queen promotion': 'c1=Q',
  'c eight queen promotion': 'c8=Q',
  'd one queen promotion': 'd1=Q',
  'd eight queen promotion': 'd8=Q',
  'e one queen promotion': 'e1=Q',
  'e eight queen promotion': 'e8=Q',
  'f one queen promotion': 'f1=Q',
  'f eight queen promotion': 'f8=Q',
  'g one queen promotion': 'g1=Q',
  'g eight queen promotion': 'g8=Q',
  'h one queen promotion': 'h1=Q',
  'h eight queen promotion': 'h8=Q',
  'a one rook promotion': 'a1=R',
  'a eight rook promotion': 'a8=R',
  'b one rook promotion': 'b1=R',
  'b eight rook promotion': 'b8=R',
  'c one rook promotion': 'c1=R',
  'c eight rook promotion': 'c8=R',
  'd one rook promotion': 'd1=R',
  'd eight rook promotion': 'd8=R',
  'e one rook promotion': 'e1=R',
  'e eight rook promotion': 'e8=R',
  'f one rook promotion': 'f1=R',
  'f eight rook promotion': 'f8=R',
  'g one rook promotion': 'g1=R',
  'g eight rook promotion': 'g8=R',
  'h one rook promotion': 'h1=R',
  'h eight rook promotion': 'h8=R',
  'a one promote to bishop': 'a1=B',
  'a eight promote to bishop': 'a8=B',
  'b one promote to bishop': 'b1=B',
  'b eight promote to bishop': 'b8=B',
  'c one promote to bishop': 'c1=B',
  'c eight promote to bishop': 'c8=B',
  'd one promote to bishop': 'd1=B',
  'd eight promote to bishop': 'd8=B',
  'e one promote to bishop': 'e1=B',
  'e eight promote to bishop': 'e8=B',
  'f one promote to bishop': 'f1=B',
  'f eight promote to bishop': 'f8=B',
  'g one promote to bishop': 'g1=B',
  'g eight promote to bishop': 'g8=B',
  'h one promote to bishop': 'h1=B',
  'h eight promote to bishop': 'h8=B',
  'a one promote to knight': 'a1=N',
  'a eight promote to knight': 'a8=N',
  'b one promote to knight': 'b1=N',
  'b eight promote to knight': 'b8=N',
  'c one promote to knight': 'c1=N',
  'c eight promote to knight': 'c8=N',
  'd one promote to knight': 'd1=N',
  'd eight promote to knight': 'd8=N',
  'e one promote to knight': 'e1=N',
  'e eight promote to knight': 'e8=N',
  'f one promote to knight': 'f1=N',
  'f eight promote to knight': 'f8=N',
  'g one promote to knight': 'g1=N',
  'g eight promote to knight': 'g8=N',
  'h one promote to knight': 'h1=N',
  'h eight promote to knight': 'h8=N',
  'a one promote to queen': 'a1=Q',
  'a eight promote to queen': 'a8=Q',
  'b one promote to queen': 'b1=Q',
  'b eight promote to queen': 'b8=Q',
  'c one promote to queen': 'c1=Q',
  'c eight promote to queen': 'c8=Q',
  'd one promote to queen': 'd1=Q',
  'd eight promote to queen': 'd8=Q',
  'e one promote to queen': 'e1=Q',
  'e eight promote to queen': 'e8=Q',
  'f one promote to queen': 'f1=Q',
  'f eight promote to queen': 'f8=Q',
  'g one promote to queen': 'g1=Q',
  'g eight promote to queen': 'g8=Q',
  'h one promote to queen': 'h1=Q',
  'h eight promote to queen': 'h8=Q',
  'a one promote to rook': 'a1=R',
  'a eight promote to rook': 'a8=R',
  'b one promote to rook': 'b1=R',
  'b eight promote to rook': 'b8=R',
  'c one promote to rook': 'c1=R',
  'c eight promote to rook': 'c8=R',
  'd one promote to rook': 'd1=R',
  'd eight promote to rook': 'd8=R',
  'e one promote to rook': 'e1=R',
  'e eight promote to rook': 'e8=R',
  'f one promote to rook': 'f1=R',
  'f eight promote to rook': 'f8=R',
  'g one promote to rook': 'g1=R',
  'g eight promote to rook': 'g8=R',
  'h one promote to rook': 'h1=R',
  'h eight promote to rook': 'h8=R',
  'a one promotes to bishop': 'a1=B',
  'a eight promotes to bishop': 'a8=B',
  'b one promotes to bishop': 'b1=B',
  'b eight promotes to bishop': 'b8=B',
  'c one promotes to bishop': 'c1=B',
  'c eight promotes to bishop': 'c8=B',
  'd one promotes to bishop': 'd1=B',
  'd eight promotes to bishop': 'd8=B',
  'e one promotes to bishop': 'e1=B',
  'e eight promotes to bishop': 'e8=B',
  'f one promotes to bishop': 'f1=B',
  'f eight promotes to bishop': 'f8=B',
  'g one promotes to bishop': 'g1=B',
  'g eight promotes to bishop': 'g8=B',
  'h one promotes to bishop': 'h1=B',
  'h eight promotes to bishop': 'h8=B',
  'a one promotes to knight': 'a1=N',
  'a eight promotes to knight': 'a8=N',
  'b one promotes to knight': 'b1=N',
  'b eight promotes to knight': 'b8=N',
  'c one promotes to knight': 'c1=N',
  'c eight promotes to knight': 'c8=N',
  'd one promotes to knight': 'd1=N',
  'd eight promotes to knight': 'd8=N',
  'e one promotes to knight': 'e1=N',
  'e eight promotes to knight': 'e8=N',
  'f one promotes to knight': 'f1=N',
  'f eight promotes to knight': 'f8=N',
  'g one promotes to knight': 'g1=N',
  'g eight promotes to knight': 'g8=N',
  'h one promotes to knight': 'h1=N',
  'h eight promotes to knight': 'h8=N',
  'a one promotes to queen': 'a1=Q',
  'a eight promotes to queen': 'a8=Q',
  'b one promotes to queen': 'b1=Q',
  'b eight promotes to queen': 'b8=Q',
  'c one promotes to queen': 'c1=Q',
  'c eight promotes to queen': 'c8=Q',
  'd one promotes to queen': 'd1=Q',
  'd eight promotes to queen': 'd8=Q',
  'e one promotes to queen': 'e1=Q',
  'e eight promotes to queen': 'e8=Q',
  'f one promotes to queen': 'f1=Q',
  'f eight promotes to queen': 'f8=Q',
  'g one promotes to queen': 'g1=Q',
  'g eight promotes to queen': 'g8=Q',
  'h one promotes to queen': 'h1=Q',
  'h eight promotes to queen': 'h8=Q',
  'a one promotes to rook': 'a1=R',
  'a eight promotes to rook': 'a8=R',
  'b one promotes to rook': 'b1=R',
  'b eight promotes to rook': 'b8=R',
  'c one promotes to rook': 'c1=R',
  'c eight promotes to rook': 'c8=R',
  'd one promotes to rook': 'd1=R',
  'd eight promotes to rook': 'd8=R',
  'e one promotes to rook': 'e1=R',
  'e eight promotes to rook': 'e8=R',
  'f one promotes to rook': 'f1=R',
  'f eight promotes to rook': 'f8=R',
  'g one promotes to rook': 'g1=R',
  'g eight promotes to rook': 'g8=R',
  'h one promotes to rook': 'h1=R',
  'h eight promotes to rook': 'h8=R',
  'a one promotion bishop': 'a1=B',
  'a eight promotion bishop': 'a8=B',
  'b one promotion bishop': 'b1=B',
  'b eight promotion bishop': 'b8=B',
  'c one promotion bishop': 'c1=B',
  'c eight promotion bishop': 'c8=B',
  'd one promotion bishop': 'd1=B',
  'd eight promotion bishop': 'd8=B',
  'e one promotion bishop': 'e1=B',
  'e eight promotion bishop': 'e8=B',
  'f one promotion bishop': 'f1=B',
  'f eight promotion bishop': 'f8=B',
  'g one promotion bishop': 'g1=B',
  'g eight promotion bishop': 'g8=B',
  'h one promotion bishop': 'h1=B',
  'h eight promotion bishop': 'h8=B',
  'a one promotion knight': 'a1=N',
  'a eight promotion knight': 'a8=N',
  'b one promotion knight': 'b1=N',
  'b eight promotion knight': 'b8=N',
  'c one promotion knight': 'c1=N',
  'c eight promotion knight': 'c8=N',
  'd one promotion knight': 'd1=N',
  'd eight promotion knight': 'd8=N',
  'e one promotion knight': 'e1=N',
  'e eight promotion knight': 'e8=N',
  'f one promotion knight': 'f1=N',
  'f eight promotion knight': 'f8=N',
  'g one promotion knight': 'g1=N',
  'g eight promotion knight': 'g8=N',
  'h one promotion knight': 'h1=N',
  'h eight promotion knight': 'h8=N',
  'a one promotion queen': 'a1=Q',
  'a eight promotion queen': 'a8=Q',
  'b one promotion queen': 'b1=Q',
  'b eight promotion queen': 'b8=Q',
  'c one promotion queen': 'c1=Q',
  'c eight promotion queen': 'c8=Q',
  'd one promotion queen': 'd1=Q',
  'd eight promotion queen': 'd8=Q',
  'e one promotion queen': 'e1=Q',
  'e eight promotion queen': 'e8=Q',
  'f one promotion queen': 'f1=Q',
  'f eight promotion queen': 'f8=Q',
  'g one promotion queen': 'g1=Q',
  'g eight promotion queen': 'g8=Q',
  'h one promotion queen': 'h1=Q',
  'h eight promotion queen': 'h8=Q',
  'a one promotion rook': 'a1=R',
  'a eight promotion rook': 'a8=R',
  'b one promotion rook': 'b1=R',
  'b eight promotion rook': 'b8=R',
  'c one promotion rook': 'c1=R',
  'c eight promotion rook': 'c8=R',
  'd one promotion rook': 'd1=R',
  'd eight promotion rook': 'd8=R',
  'e one promotion rook': 'e1=R',
  'e eight promotion rook': 'e8=R',
  'f one promotion rook': 'f1=R',
  'f eight promotion rook': 'f8=R',
  'g one promotion rook': 'g1=R',
  'g eight promotion rook': 'g8=R',
  'h one promotion rook': 'h1=R',
  'h eight promotion rook': 'h8=R',

  // Pawn push promotions without explicit piece (default: queen)
  'a one promote': 'a1=Q',
  'a eight promote': 'a8=Q',
  'b one promote': 'b1=Q',
  'b eight promote': 'b8=Q',
  'c one promote': 'c1=Q',
  'c eight promote': 'c8=Q',
  'd one promote': 'd1=Q',
  'd eight promote': 'd8=Q',
  'e one promote': 'e1=Q',
  'e eight promote': 'e8=Q',
  'f one promote': 'f1=Q',
  'f eight promote': 'f8=Q',
  'g one promote': 'g1=Q',
  'g eight promote': 'g8=Q',
  'h one promote': 'h1=Q',
  'h eight promote': 'h8=Q',
  'a one promotes': 'a1=Q',
  'a eight promotes': 'a8=Q',
  'b one promotes': 'b1=Q',
  'b eight promotes': 'b8=Q',
  'c one promotes': 'c1=Q',
  'c eight promotes': 'c8=Q',
  'd one promotes': 'd1=Q',
  'd eight promotes': 'd8=Q',
  'e one promotes': 'e1=Q',
  'e eight promotes': 'e8=Q',
  'f one promotes': 'f1=Q',
  'f eight promotes': 'f8=Q',
  'g one promotes': 'g1=Q',
  'g eight promotes': 'g8=Q',
  'h one promotes': 'h1=Q',
  'h eight promotes': 'h8=Q',
  'a one promotion': 'a1=Q',
  'a eight promotion': 'a8=Q',
  'b one promotion': 'b1=Q',
  'b eight promotion': 'b8=Q',
  'c one promotion': 'c1=Q',
  'c eight promotion': 'c8=Q',
  'd one promotion': 'd1=Q',
  'd eight promotion': 'd8=Q',
  'e one promotion': 'e1=Q',
  'e eight promotion': 'e8=Q',
  'f one promotion': 'f1=Q',
  'f eight promotion': 'f8=Q',
  'g one promotion': 'g1=Q',
  'g eight promotion': 'g8=Q',
  'h one promotion': 'h1=Q',
  'h eight promotion': 'h8=Q',
};
