name: '@konker.dev/konker.dev / CD'

on:
  workflow_dispatch:
    inputs:
      extra_args:
        description: "TurboRepo Extra Args"
        required: false
        type: string

  push:
    branches:
      - 'main'
    paths:
      - 'apps/konker.dev/src/**'
      - 'apps/konker.dev/public/**'
      - 'apps/konker.dev/assets/**'

env:
  AWS_S3_BUCKET: ${{ secrets.KONKER_DOT_DEV_AWS_S3_BUCKET }}
  AWS_CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.KONKER_DOT_DEV_AWS_CLOUDFRONT_DISTRIBUTION_ID }}
  AWS_DEFAULT_REGION: 'eu-west-1'
  CWD: './apps/konker.dev'
  SOURCE_DIR: './apps/konker.dev/www'
  DEST_DIR: '/www'
  TURBO_TELEMETRY_DISABLED: 1
  TURBO_FILTER_ARG: '--filter=@konker.dev/konker.dev'
  TURBO_EXTRA_ARGS: ${{ inputs.extra_args }}

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: CD
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.KONKER_DOT_DEV_DOMAIN_USER_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.KONKER_DOT_DEV_DOMAIN_USER_AWS_ACCESS_KEY_SECRET }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: '9.6.0'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Build
        run: pnpm run build ${{ env.TURBO_FILTER_ARG }} ${{ env.TURBO_EXTRA_ARGS }}

      - name: Sync files to S3
        run: |
          aws s3 sync ${{ env.SOURCE_DIR }} s3://${{ env.AWS_S3_BUCKET }}${{ env.DEST_DIR }} --delete --exclude '.*git*'

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.AWS_CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"
