name: CI

on:
  pull_request:
    branches:
      - main
      - development

  workflow_dispatch:
    inputs:
      filter:
        description: "TurboRepo Filter"
        required: false
        type: string
      extra_args:
        description: "TurboRepo Extra Args"
        required: false
        type: string

env:
  NODE_AUTH_TOKEN: ${{ secrets.PRIVATE_NPM_TOKEN }}
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.base_ref || github.event.before || 'HEAD^' }}
  TURBO_TELEMETRY_DISABLED: '1'
  TURBO_FILTER_ARG: ${{ (inputs.filter == '' && '--affected') || format('--filter={0}', inputs.filter) }}
  TURBO_EXTRA_ARGS: ${{ inputs.extra_args }}

jobs:
  ci:
    permissions:
      id-token: write
      contents: read
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: CI
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # Explicitly fetch the target branch
      - name: Fetch base branch
        if: github.event_name == 'pull_request'
        run: |
          git fetch origin ${{ github.base_ref }}:${{ github.base_ref }}
          git branch --track ${{ github.base_ref }} origin/${{ github.base_ref }} || echo "Branch already tracked or other issue, continuing..."

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '22'

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: '9.6.0'

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Configure AWS credentials for Turborepo cache
        uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::047719649582:role/infra/ci-turborepo-cache-konker-dev
          aws-region: eu-west-1

      - name: TurboRepo Remote Cache Server
        uses: trappar/turborepo-remote-cache-gh-action@main
        with:
          storage-provider: s3
          storage-path: konkerdotdev-turborepo-cache
          team-id: turbo/konker.dev

      - name: Run Checks
        run: pnpm run ci ${{ env.TURBO_FILTER_ARG }} ${{ env.TURBO_EXTRA_ARGS }}
