name: Update Codecov

on:
  workflow_dispatch:
    inputs:
      filter:
        description: "TurboRepo Filter"
        required: false
        type: string
      extra_args:
        description: "TurboRepo Extra Args"
        required: false
        type: string

env:
  NODE_AUTH_TOKEN: "${{ secrets.PRIVATE_NPM_TOKEN }}"
  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  TURBO_TELEMETRY_DISABLED: 1
  TURBO_FILTER_ARG: ${{ (inputs.filter == '' && '--affected') || format('--filter={0}', inputs.filter) }}
  TURBO_EXTRA_ARGS: ${{ inputs.extra_args }}

jobs:
  cd:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    name: Codecov
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org/"

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: "9.6.0"

      - name: Install Dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Tests
        run: pnpm run test ${{ env.TURBO_FILTER_ARG }} ${{ env.TURBO_EXTRA_ARGS }}

      - name: Upload to Codecov
        run: pnpm run codecov ${{ env.TURBO_FILTER_ARG }} ${{ env.TURBO_EXTRA_ARGS }}
